// Code generated by ent, DO NOT EDIT.

package item

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the item type in the database.
	Label = "item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldInStock holds the string denoting the in_stock field in the database.
	FieldInStock = "in_stock"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// EdgeSelectedCustomItems holds the string denoting the selected_custom_items edge name in mutations.
	EdgeSelectedCustomItems = "selected_custom_items"
	// Table holds the table name of the item in the database.
	Table = "items"
	// SelectedCustomItemsTable is the table that holds the selected_custom_items relation/edge. The primary key declared below.
	SelectedCustomItemsTable = "selected_custom_item_selected_variants"
	// SelectedCustomItemsInverseTable is the table name for the SelectedCustomItem entity.
	// It exists in this package in order to avoid circular dependency with the "selectedcustomitem" package.
	SelectedCustomItemsInverseTable = "selected_custom_items"
)

// Columns holds all SQL columns for item fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldPrice,
	FieldImage,
	FieldInStock,
	FieldNotes,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "items"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"custom_item_variants",
}

var (
	// SelectedCustomItemsPrimaryKey and SelectedCustomItemsColumn2 are the table columns denoting the
	// primary key for the selected_custom_items relation (M2M).
	SelectedCustomItemsPrimaryKey = []string{"selected_custom_item_id", "item_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Item queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByInStock orders the results by the in_stock field.
func ByInStock(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInStock, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// BySelectedCustomItemsCount orders the results by selected_custom_items count.
func BySelectedCustomItemsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSelectedCustomItemsStep(), opts...)
	}
}

// BySelectedCustomItems orders the results by selected_custom_items terms.
func BySelectedCustomItems(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSelectedCustomItemsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSelectedCustomItemsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SelectedCustomItemsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, SelectedCustomItemsTable, SelectedCustomItemsPrimaryKey...),
	)
}
