// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/codecrafter404/bubble/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/orderitem"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// CustomItem is the client for interacting with the CustomItem builders.
	CustomItem *CustomItemClient
	// Item is the client for interacting with the Item builders.
	Item *ItemClient
	// Order is the client for interacting with the Order builders.
	Order *OrderClient
	// OrderCustomItem is the client for interacting with the OrderCustomItem builders.
	OrderCustomItem *OrderCustomItemClient
	// OrderItem is the client for interacting with the OrderItem builders.
	OrderItem *OrderItemClient
	// SelectedCustomItem is the client for interacting with the SelectedCustomItem builders.
	SelectedCustomItem *SelectedCustomItemClient
	// additional fields for node api
	tables tables
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.CustomItem = NewCustomItemClient(c.config)
	c.Item = NewItemClient(c.config)
	c.Order = NewOrderClient(c.config)
	c.OrderCustomItem = NewOrderCustomItemClient(c.config)
	c.OrderItem = NewOrderItemClient(c.config)
	c.SelectedCustomItem = NewSelectedCustomItemClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		CustomItem:         NewCustomItemClient(cfg),
		Item:               NewItemClient(cfg),
		Order:              NewOrderClient(cfg),
		OrderCustomItem:    NewOrderCustomItemClient(cfg),
		OrderItem:          NewOrderItemClient(cfg),
		SelectedCustomItem: NewSelectedCustomItemClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:                ctx,
		config:             cfg,
		CustomItem:         NewCustomItemClient(cfg),
		Item:               NewItemClient(cfg),
		Order:              NewOrderClient(cfg),
		OrderCustomItem:    NewOrderCustomItemClient(cfg),
		OrderItem:          NewOrderItemClient(cfg),
		SelectedCustomItem: NewSelectedCustomItemClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		CustomItem.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	for _, n := range []interface{ Use(...Hook) }{
		c.CustomItem, c.Item, c.Order, c.OrderCustomItem, c.OrderItem,
		c.SelectedCustomItem,
	} {
		n.Use(hooks...)
	}
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	for _, n := range []interface{ Intercept(...Interceptor) }{
		c.CustomItem, c.Item, c.Order, c.OrderCustomItem, c.OrderItem,
		c.SelectedCustomItem,
	} {
		n.Intercept(interceptors...)
	}
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *CustomItemMutation:
		return c.CustomItem.mutate(ctx, m)
	case *ItemMutation:
		return c.Item.mutate(ctx, m)
	case *OrderMutation:
		return c.Order.mutate(ctx, m)
	case *OrderCustomItemMutation:
		return c.OrderCustomItem.mutate(ctx, m)
	case *OrderItemMutation:
		return c.OrderItem.mutate(ctx, m)
	case *SelectedCustomItemMutation:
		return c.SelectedCustomItem.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// CustomItemClient is a client for the CustomItem schema.
type CustomItemClient struct {
	config
}

// NewCustomItemClient returns a client for the CustomItem from the given config.
func NewCustomItemClient(c config) *CustomItemClient {
	return &CustomItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `customitem.Hooks(f(g(h())))`.
func (c *CustomItemClient) Use(hooks ...Hook) {
	c.hooks.CustomItem = append(c.hooks.CustomItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `customitem.Intercept(f(g(h())))`.
func (c *CustomItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.CustomItem = append(c.inters.CustomItem, interceptors...)
}

// Create returns a builder for creating a CustomItem entity.
func (c *CustomItemClient) Create() *CustomItemCreate {
	mutation := newCustomItemMutation(c.config, OpCreate)
	return &CustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of CustomItem entities.
func (c *CustomItemClient) CreateBulk(builders ...*CustomItemCreate) *CustomItemCreateBulk {
	return &CustomItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *CustomItemClient) MapCreateBulk(slice any, setFunc func(*CustomItemCreate, int)) *CustomItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &CustomItemCreateBulk{err: fmt.Errorf("calling to CustomItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*CustomItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &CustomItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for CustomItem.
func (c *CustomItemClient) Update() *CustomItemUpdate {
	mutation := newCustomItemMutation(c.config, OpUpdate)
	return &CustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *CustomItemClient) UpdateOne(_m *CustomItem) *CustomItemUpdateOne {
	mutation := newCustomItemMutation(c.config, OpUpdateOne, withCustomItem(_m))
	return &CustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *CustomItemClient) UpdateOneID(id int) *CustomItemUpdateOne {
	mutation := newCustomItemMutation(c.config, OpUpdateOne, withCustomItemID(id))
	return &CustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for CustomItem.
func (c *CustomItemClient) Delete() *CustomItemDelete {
	mutation := newCustomItemMutation(c.config, OpDelete)
	return &CustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *CustomItemClient) DeleteOne(_m *CustomItem) *CustomItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *CustomItemClient) DeleteOneID(id int) *CustomItemDeleteOne {
	builder := c.Delete().Where(customitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &CustomItemDeleteOne{builder}
}

// Query returns a query builder for CustomItem.
func (c *CustomItemClient) Query() *CustomItemQuery {
	return &CustomItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeCustomItem},
		inters: c.Interceptors(),
	}
}

// Get returns a CustomItem entity by its id.
func (c *CustomItemClient) Get(ctx context.Context, id int) (*CustomItem, error) {
	return c.Query().Where(customitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *CustomItemClient) GetX(ctx context.Context, id int) *CustomItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryVariants queries the variants edge of a CustomItem.
func (c *CustomItemClient) QueryVariants(_m *CustomItem) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(customitem.Table, customitem.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, customitem.VariantsTable, customitem.VariantsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *CustomItemClient) Hooks() []Hook {
	return c.hooks.CustomItem
}

// Interceptors returns the client interceptors.
func (c *CustomItemClient) Interceptors() []Interceptor {
	return c.inters.CustomItem
}

func (c *CustomItemClient) mutate(ctx context.Context, m *CustomItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&CustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&CustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&CustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&CustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown CustomItem mutation op: %q", m.Op())
	}
}

// ItemClient is a client for the Item schema.
type ItemClient struct {
	config
}

// NewItemClient returns a client for the Item from the given config.
func NewItemClient(c config) *ItemClient {
	return &ItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `item.Hooks(f(g(h())))`.
func (c *ItemClient) Use(hooks ...Hook) {
	c.hooks.Item = append(c.hooks.Item, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `item.Intercept(f(g(h())))`.
func (c *ItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.Item = append(c.inters.Item, interceptors...)
}

// Create returns a builder for creating a Item entity.
func (c *ItemClient) Create() *ItemCreate {
	mutation := newItemMutation(c.config, OpCreate)
	return &ItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Item entities.
func (c *ItemClient) CreateBulk(builders ...*ItemCreate) *ItemCreateBulk {
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ItemClient) MapCreateBulk(slice any, setFunc func(*ItemCreate, int)) *ItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ItemCreateBulk{err: fmt.Errorf("calling to ItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Item.
func (c *ItemClient) Update() *ItemUpdate {
	mutation := newItemMutation(c.config, OpUpdate)
	return &ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ItemClient) UpdateOne(_m *Item) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItem(_m))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ItemClient) UpdateOneID(id int) *ItemUpdateOne {
	mutation := newItemMutation(c.config, OpUpdateOne, withItemID(id))
	return &ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Item.
func (c *ItemClient) Delete() *ItemDelete {
	mutation := newItemMutation(c.config, OpDelete)
	return &ItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ItemClient) DeleteOne(_m *Item) *ItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ItemClient) DeleteOneID(id int) *ItemDeleteOne {
	builder := c.Delete().Where(item.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ItemDeleteOne{builder}
}

// Query returns a query builder for Item.
func (c *ItemClient) Query() *ItemQuery {
	return &ItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeItem},
		inters: c.Interceptors(),
	}
}

// Get returns a Item entity by its id.
func (c *ItemClient) Get(ctx context.Context, id int) (*Item, error) {
	return c.Query().Where(item.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ItemClient) GetX(ctx context.Context, id int) *Item {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySelectedCustomItems queries the selected_custom_items edge of a Item.
func (c *ItemClient) QuerySelectedCustomItems(_m *Item) *SelectedCustomItemQuery {
	query := (&SelectedCustomItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(item.Table, item.FieldID, id),
			sqlgraph.To(selectedcustomitem.Table, selectedcustomitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, item.SelectedCustomItemsTable, item.SelectedCustomItemsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ItemClient) Hooks() []Hook {
	return c.hooks.Item
}

// Interceptors returns the client interceptors.
func (c *ItemClient) Interceptors() []Interceptor {
	return c.inters.Item
}

func (c *ItemClient) mutate(ctx context.Context, m *ItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Item mutation op: %q", m.Op())
	}
}

// OrderClient is a client for the Order schema.
type OrderClient struct {
	config
}

// NewOrderClient returns a client for the Order from the given config.
func NewOrderClient(c config) *OrderClient {
	return &OrderClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `order.Hooks(f(g(h())))`.
func (c *OrderClient) Use(hooks ...Hook) {
	c.hooks.Order = append(c.hooks.Order, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `order.Intercept(f(g(h())))`.
func (c *OrderClient) Intercept(interceptors ...Interceptor) {
	c.inters.Order = append(c.inters.Order, interceptors...)
}

// Create returns a builder for creating a Order entity.
func (c *OrderClient) Create() *OrderCreate {
	mutation := newOrderMutation(c.config, OpCreate)
	return &OrderCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Order entities.
func (c *OrderClient) CreateBulk(builders ...*OrderCreate) *OrderCreateBulk {
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderClient) MapCreateBulk(slice any, setFunc func(*OrderCreate, int)) *OrderCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderCreateBulk{err: fmt.Errorf("calling to OrderClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Order.
func (c *OrderClient) Update() *OrderUpdate {
	mutation := newOrderMutation(c.config, OpUpdate)
	return &OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderClient) UpdateOne(_m *Order) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrder(_m))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderClient) UpdateOneID(id int) *OrderUpdateOne {
	mutation := newOrderMutation(c.config, OpUpdateOne, withOrderID(id))
	return &OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Order.
func (c *OrderClient) Delete() *OrderDelete {
	mutation := newOrderMutation(c.config, OpDelete)
	return &OrderDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderClient) DeleteOne(_m *Order) *OrderDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderClient) DeleteOneID(id int) *OrderDeleteOne {
	builder := c.Delete().Where(order.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderDeleteOne{builder}
}

// Query returns a query builder for Order.
func (c *OrderClient) Query() *OrderQuery {
	return &OrderQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrder},
		inters: c.Interceptors(),
	}
}

// Get returns a Order entity by its id.
func (c *OrderClient) Get(ctx context.Context, id int) (*Order, error) {
	return c.Query().Where(order.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderClient) GetX(ctx context.Context, id int) *Order {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItems queries the items edge of a Order.
func (c *OrderClient) QueryItems(_m *Order) *OrderItemQuery {
	query := (&OrderItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, id),
			sqlgraph.To(orderitem.Table, orderitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.ItemsTable, order.ItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCustomItems queries the custom_items edge of a Order.
func (c *OrderClient) QueryCustomItems(_m *Order) *OrderCustomItemQuery {
	query := (&OrderCustomItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(order.Table, order.FieldID, id),
			sqlgraph.To(ordercustomitem.Table, ordercustomitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, order.CustomItemsTable, order.CustomItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderClient) Hooks() []Hook {
	return c.hooks.Order
}

// Interceptors returns the client interceptors.
func (c *OrderClient) Interceptors() []Interceptor {
	return c.inters.Order
}

func (c *OrderClient) mutate(ctx context.Context, m *OrderMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Order mutation op: %q", m.Op())
	}
}

// OrderCustomItemClient is a client for the OrderCustomItem schema.
type OrderCustomItemClient struct {
	config
}

// NewOrderCustomItemClient returns a client for the OrderCustomItem from the given config.
func NewOrderCustomItemClient(c config) *OrderCustomItemClient {
	return &OrderCustomItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ordercustomitem.Hooks(f(g(h())))`.
func (c *OrderCustomItemClient) Use(hooks ...Hook) {
	c.hooks.OrderCustomItem = append(c.hooks.OrderCustomItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ordercustomitem.Intercept(f(g(h())))`.
func (c *OrderCustomItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.OrderCustomItem = append(c.inters.OrderCustomItem, interceptors...)
}

// Create returns a builder for creating a OrderCustomItem entity.
func (c *OrderCustomItemClient) Create() *OrderCustomItemCreate {
	mutation := newOrderCustomItemMutation(c.config, OpCreate)
	return &OrderCustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OrderCustomItem entities.
func (c *OrderCustomItemClient) CreateBulk(builders ...*OrderCustomItemCreate) *OrderCustomItemCreateBulk {
	return &OrderCustomItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderCustomItemClient) MapCreateBulk(slice any, setFunc func(*OrderCustomItemCreate, int)) *OrderCustomItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderCustomItemCreateBulk{err: fmt.Errorf("calling to OrderCustomItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderCustomItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderCustomItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OrderCustomItem.
func (c *OrderCustomItemClient) Update() *OrderCustomItemUpdate {
	mutation := newOrderCustomItemMutation(c.config, OpUpdate)
	return &OrderCustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderCustomItemClient) UpdateOne(_m *OrderCustomItem) *OrderCustomItemUpdateOne {
	mutation := newOrderCustomItemMutation(c.config, OpUpdateOne, withOrderCustomItem(_m))
	return &OrderCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderCustomItemClient) UpdateOneID(id int) *OrderCustomItemUpdateOne {
	mutation := newOrderCustomItemMutation(c.config, OpUpdateOne, withOrderCustomItemID(id))
	return &OrderCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OrderCustomItem.
func (c *OrderCustomItemClient) Delete() *OrderCustomItemDelete {
	mutation := newOrderCustomItemMutation(c.config, OpDelete)
	return &OrderCustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderCustomItemClient) DeleteOne(_m *OrderCustomItem) *OrderCustomItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderCustomItemClient) DeleteOneID(id int) *OrderCustomItemDeleteOne {
	builder := c.Delete().Where(ordercustomitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderCustomItemDeleteOne{builder}
}

// Query returns a query builder for OrderCustomItem.
func (c *OrderCustomItemClient) Query() *OrderCustomItemQuery {
	return &OrderCustomItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrderCustomItem},
		inters: c.Interceptors(),
	}
}

// Get returns a OrderCustomItem entity by its id.
func (c *OrderCustomItemClient) Get(ctx context.Context, id int) (*OrderCustomItem, error) {
	return c.Query().Where(ordercustomitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderCustomItemClient) GetX(ctx context.Context, id int) *OrderCustomItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySelectedCustomItems queries the selected_custom_items edge of a OrderCustomItem.
func (c *OrderCustomItemClient) QuerySelectedCustomItems(_m *OrderCustomItem) *SelectedCustomItemQuery {
	query := (&SelectedCustomItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ordercustomitem.Table, ordercustomitem.FieldID, id),
			sqlgraph.To(selectedcustomitem.Table, selectedcustomitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ordercustomitem.SelectedCustomItemsTable, ordercustomitem.SelectedCustomItemsColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryMasterCustomItem queries the master_custom_item edge of a OrderCustomItem.
func (c *OrderCustomItemClient) QueryMasterCustomItem(_m *OrderCustomItem) *CustomItemQuery {
	query := (&CustomItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ordercustomitem.Table, ordercustomitem.FieldID, id),
			sqlgraph.To(customitem.Table, customitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ordercustomitem.MasterCustomItemTable, ordercustomitem.MasterCustomItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrder queries the order edge of a OrderCustomItem.
func (c *OrderCustomItemClient) QueryOrder(_m *OrderCustomItem) *OrderQuery {
	query := (&OrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(ordercustomitem.Table, ordercustomitem.FieldID, id),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ordercustomitem.OrderTable, ordercustomitem.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderCustomItemClient) Hooks() []Hook {
	return c.hooks.OrderCustomItem
}

// Interceptors returns the client interceptors.
func (c *OrderCustomItemClient) Interceptors() []Interceptor {
	return c.inters.OrderCustomItem
}

func (c *OrderCustomItemClient) mutate(ctx context.Context, m *OrderCustomItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderCustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderCustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderCustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OrderCustomItem mutation op: %q", m.Op())
	}
}

// OrderItemClient is a client for the OrderItem schema.
type OrderItemClient struct {
	config
}

// NewOrderItemClient returns a client for the OrderItem from the given config.
func NewOrderItemClient(c config) *OrderItemClient {
	return &OrderItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `orderitem.Hooks(f(g(h())))`.
func (c *OrderItemClient) Use(hooks ...Hook) {
	c.hooks.OrderItem = append(c.hooks.OrderItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `orderitem.Intercept(f(g(h())))`.
func (c *OrderItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.OrderItem = append(c.inters.OrderItem, interceptors...)
}

// Create returns a builder for creating a OrderItem entity.
func (c *OrderItemClient) Create() *OrderItemCreate {
	mutation := newOrderItemMutation(c.config, OpCreate)
	return &OrderItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OrderItem entities.
func (c *OrderItemClient) CreateBulk(builders ...*OrderItemCreate) *OrderItemCreateBulk {
	return &OrderItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OrderItemClient) MapCreateBulk(slice any, setFunc func(*OrderItemCreate, int)) *OrderItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OrderItemCreateBulk{err: fmt.Errorf("calling to OrderItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OrderItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OrderItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OrderItem.
func (c *OrderItemClient) Update() *OrderItemUpdate {
	mutation := newOrderItemMutation(c.config, OpUpdate)
	return &OrderItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OrderItemClient) UpdateOne(_m *OrderItem) *OrderItemUpdateOne {
	mutation := newOrderItemMutation(c.config, OpUpdateOne, withOrderItem(_m))
	return &OrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OrderItemClient) UpdateOneID(id int) *OrderItemUpdateOne {
	mutation := newOrderItemMutation(c.config, OpUpdateOne, withOrderItemID(id))
	return &OrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OrderItem.
func (c *OrderItemClient) Delete() *OrderItemDelete {
	mutation := newOrderItemMutation(c.config, OpDelete)
	return &OrderItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OrderItemClient) DeleteOne(_m *OrderItem) *OrderItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OrderItemClient) DeleteOneID(id int) *OrderItemDeleteOne {
	builder := c.Delete().Where(orderitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OrderItemDeleteOne{builder}
}

// Query returns a query builder for OrderItem.
func (c *OrderItemClient) Query() *OrderItemQuery {
	return &OrderItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOrderItem},
		inters: c.Interceptors(),
	}
}

// Get returns a OrderItem entity by its id.
func (c *OrderItemClient) Get(ctx context.Context, id int) (*OrderItem, error) {
	return c.Query().Where(orderitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OrderItemClient) GetX(ctx context.Context, id int) *OrderItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryItem queries the item edge of a OrderItem.
func (c *OrderItemClient) QueryItem(_m *OrderItem) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderitem.Table, orderitem.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, orderitem.ItemTable, orderitem.ItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryOrder queries the order edge of a OrderItem.
func (c *OrderItemClient) QueryOrder(_m *OrderItem) *OrderQuery {
	query := (&OrderClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(orderitem.Table, orderitem.FieldID, id),
			sqlgraph.To(order.Table, order.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, orderitem.OrderTable, orderitem.OrderColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *OrderItemClient) Hooks() []Hook {
	return c.hooks.OrderItem
}

// Interceptors returns the client interceptors.
func (c *OrderItemClient) Interceptors() []Interceptor {
	return c.inters.OrderItem
}

func (c *OrderItemClient) mutate(ctx context.Context, m *OrderItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OrderItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OrderItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OrderItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OrderItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OrderItem mutation op: %q", m.Op())
	}
}

// SelectedCustomItemClient is a client for the SelectedCustomItem schema.
type SelectedCustomItemClient struct {
	config
}

// NewSelectedCustomItemClient returns a client for the SelectedCustomItem from the given config.
func NewSelectedCustomItemClient(c config) *SelectedCustomItemClient {
	return &SelectedCustomItemClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `selectedcustomitem.Hooks(f(g(h())))`.
func (c *SelectedCustomItemClient) Use(hooks ...Hook) {
	c.hooks.SelectedCustomItem = append(c.hooks.SelectedCustomItem, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `selectedcustomitem.Intercept(f(g(h())))`.
func (c *SelectedCustomItemClient) Intercept(interceptors ...Interceptor) {
	c.inters.SelectedCustomItem = append(c.inters.SelectedCustomItem, interceptors...)
}

// Create returns a builder for creating a SelectedCustomItem entity.
func (c *SelectedCustomItemClient) Create() *SelectedCustomItemCreate {
	mutation := newSelectedCustomItemMutation(c.config, OpCreate)
	return &SelectedCustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of SelectedCustomItem entities.
func (c *SelectedCustomItemClient) CreateBulk(builders ...*SelectedCustomItemCreate) *SelectedCustomItemCreateBulk {
	return &SelectedCustomItemCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *SelectedCustomItemClient) MapCreateBulk(slice any, setFunc func(*SelectedCustomItemCreate, int)) *SelectedCustomItemCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &SelectedCustomItemCreateBulk{err: fmt.Errorf("calling to SelectedCustomItemClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*SelectedCustomItemCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &SelectedCustomItemCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for SelectedCustomItem.
func (c *SelectedCustomItemClient) Update() *SelectedCustomItemUpdate {
	mutation := newSelectedCustomItemMutation(c.config, OpUpdate)
	return &SelectedCustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *SelectedCustomItemClient) UpdateOne(_m *SelectedCustomItem) *SelectedCustomItemUpdateOne {
	mutation := newSelectedCustomItemMutation(c.config, OpUpdateOne, withSelectedCustomItem(_m))
	return &SelectedCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *SelectedCustomItemClient) UpdateOneID(id int) *SelectedCustomItemUpdateOne {
	mutation := newSelectedCustomItemMutation(c.config, OpUpdateOne, withSelectedCustomItemID(id))
	return &SelectedCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for SelectedCustomItem.
func (c *SelectedCustomItemClient) Delete() *SelectedCustomItemDelete {
	mutation := newSelectedCustomItemMutation(c.config, OpDelete)
	return &SelectedCustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *SelectedCustomItemClient) DeleteOne(_m *SelectedCustomItem) *SelectedCustomItemDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *SelectedCustomItemClient) DeleteOneID(id int) *SelectedCustomItemDeleteOne {
	builder := c.Delete().Where(selectedcustomitem.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &SelectedCustomItemDeleteOne{builder}
}

// Query returns a query builder for SelectedCustomItem.
func (c *SelectedCustomItemClient) Query() *SelectedCustomItemQuery {
	return &SelectedCustomItemQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeSelectedCustomItem},
		inters: c.Interceptors(),
	}
}

// Get returns a SelectedCustomItem entity by its id.
func (c *SelectedCustomItemClient) Get(ctx context.Context, id int) (*SelectedCustomItem, error) {
	return c.Query().Where(selectedcustomitem.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *SelectedCustomItemClient) GetX(ctx context.Context, id int) *SelectedCustomItem {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QuerySelectedVariants queries the selected_variants edge of a SelectedCustomItem.
func (c *SelectedCustomItemClient) QuerySelectedVariants(_m *SelectedCustomItem) *ItemQuery {
	query := (&ItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(selectedcustomitem.Table, selectedcustomitem.FieldID, id),
			sqlgraph.To(item.Table, item.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, selectedcustomitem.SelectedVariantsTable, selectedcustomitem.SelectedVariantsPrimaryKey...),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// QueryCustomItem queries the custom_item edge of a SelectedCustomItem.
func (c *SelectedCustomItemClient) QueryCustomItem(_m *SelectedCustomItem) *CustomItemQuery {
	query := (&CustomItemClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := _m.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(selectedcustomitem.Table, selectedcustomitem.FieldID, id),
			sqlgraph.To(customitem.Table, customitem.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, selectedcustomitem.CustomItemTable, selectedcustomitem.CustomItemColumn),
		)
		fromV = sqlgraph.Neighbors(_m.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *SelectedCustomItemClient) Hooks() []Hook {
	return c.hooks.SelectedCustomItem
}

// Interceptors returns the client interceptors.
func (c *SelectedCustomItemClient) Interceptors() []Interceptor {
	return c.inters.SelectedCustomItem
}

func (c *SelectedCustomItemClient) mutate(ctx context.Context, m *SelectedCustomItemMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&SelectedCustomItemCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&SelectedCustomItemUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&SelectedCustomItemUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&SelectedCustomItemDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown SelectedCustomItem mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		CustomItem, Item, Order, OrderCustomItem, OrderItem,
		SelectedCustomItem []ent.Hook
	}
	inters struct {
		CustomItem, Item, Order, OrderCustomItem, OrderItem,
		SelectedCustomItem []ent.Interceptor
	}
)
