// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codecrafter404/bubble/ent/customitem"
)

// CustomItem is the model entity for the CustomItem schema.
type CustomItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// if false then one or more variants can be selected at once
	AllowOnlyOne bool `json:"allow_only_one,omitempty"`
	// The id of the previous to selectable custom item
	Prev *int `json:"prev,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the CustomItemQuery when eager-loading is set.
	Edges        CustomItemEdges `json:"edges"`
	selectValues sql.SelectValues
}

// CustomItemEdges holds the relations/edges for other nodes in the graph.
type CustomItemEdges struct {
	// Variants holds the value of the variants edge.
	Variants []*Item `json:"variants,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
	// totalCount holds the count of the edges above.
	totalCount [1]map[string]int

	namedVariants map[string][]*Item
}

// VariantsOrErr returns the Variants value or an error if the edge
// was not loaded in eager-loading.
func (e CustomItemEdges) VariantsOrErr() ([]*Item, error) {
	if e.loadedTypes[0] {
		return e.Variants, nil
	}
	return nil, &NotLoadedError{edge: "variants"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*CustomItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case customitem.FieldAllowOnlyOne:
			values[i] = new(sql.NullBool)
		case customitem.FieldID, customitem.FieldPrev:
			values[i] = new(sql.NullInt64)
		case customitem.FieldName:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the CustomItem fields.
func (_m *CustomItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case customitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case customitem.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case customitem.FieldAllowOnlyOne:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_only_one", values[i])
			} else if value.Valid {
				_m.AllowOnlyOne = value.Bool
			}
		case customitem.FieldPrev:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field prev", values[i])
			} else if value.Valid {
				_m.Prev = new(int)
				*_m.Prev = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the CustomItem.
// This includes values selected through modifiers, order, etc.
func (_m *CustomItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVariants queries the "variants" edge of the CustomItem entity.
func (_m *CustomItem) QueryVariants() *ItemQuery {
	return NewCustomItemClient(_m.config).QueryVariants(_m)
}

// Update returns a builder for updating this CustomItem.
// Note that you need to call CustomItem.Unwrap() before calling this method if this CustomItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *CustomItem) Update() *CustomItemUpdateOne {
	return NewCustomItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the CustomItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *CustomItem) Unwrap() *CustomItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: CustomItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *CustomItem) String() string {
	var builder strings.Builder
	builder.WriteString("CustomItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("allow_only_one=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowOnlyOne))
	builder.WriteString(", ")
	if v := _m.Prev; v != nil {
		builder.WriteString("prev=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// NamedVariants returns the Variants named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *CustomItem) NamedVariants(name string) ([]*Item, error) {
	if _m.Edges.namedVariants == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedVariants[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *CustomItem) appendNamedVariants(name string, edges ...*Item) {
	if _m.Edges.namedVariants == nil {
		_m.Edges.namedVariants = make(map[string][]*Item)
	}
	if len(edges) == 0 {
		_m.Edges.namedVariants[name] = []*Item{}
	} else {
		_m.Edges.namedVariants[name] = append(_m.Edges.namedVariants[name], edges...)
	}
}

// CustomItems is a parsable slice of CustomItem.
type CustomItems []*CustomItem
