// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
)

// CustomItemCreate is the builder for creating a CustomItem entity.
type CustomItemCreate struct {
	config
	mutation *CustomItemMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *CustomItemCreate) SetName(v string) *CustomItemCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAllowOnlyOne sets the "allow_only_one" field.
func (_c *CustomItemCreate) SetAllowOnlyOne(v bool) *CustomItemCreate {
	_c.mutation.SetAllowOnlyOne(v)
	return _c
}

// SetPrev sets the "prev" field.
func (_c *CustomItemCreate) SetPrev(v int) *CustomItemCreate {
	_c.mutation.SetPrev(v)
	return _c
}

// SetNillablePrev sets the "prev" field if the given value is not nil.
func (_c *CustomItemCreate) SetNillablePrev(v *int) *CustomItemCreate {
	if v != nil {
		_c.SetPrev(*v)
	}
	return _c
}

// AddVariantIDs adds the "variants" edge to the Item entity by IDs.
func (_c *CustomItemCreate) AddVariantIDs(ids ...int) *CustomItemCreate {
	_c.mutation.AddVariantIDs(ids...)
	return _c
}

// AddVariants adds the "variants" edges to the Item entity.
func (_c *CustomItemCreate) AddVariants(v ...*Item) *CustomItemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddVariantIDs(ids...)
}

// Mutation returns the CustomItemMutation object of the builder.
func (_c *CustomItemCreate) Mutation() *CustomItemMutation {
	return _c.mutation
}

// Save creates the CustomItem in the database.
func (_c *CustomItemCreate) Save(ctx context.Context) (*CustomItem, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomItemCreate) SaveX(ctx context.Context) *CustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomItemCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "CustomItem.name"`)}
	}
	if _, ok := _c.mutation.AllowOnlyOne(); !ok {
		return &ValidationError{Name: "allow_only_one", err: errors.New(`ent: missing required field "CustomItem.allow_only_one"`)}
	}
	if len(_c.mutation.VariantsIDs()) == 0 {
		return &ValidationError{Name: "variants", err: errors.New(`ent: missing required edge "CustomItem.variants"`)}
	}
	return nil
}

func (_c *CustomItemCreate) sqlSave(ctx context.Context) (*CustomItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomItemCreate) createSpec() (*CustomItem, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customitem.Table, sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(customitem.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AllowOnlyOne(); ok {
		_spec.SetField(customitem.FieldAllowOnlyOne, field.TypeBool, value)
		_node.AllowOnlyOne = value
	}
	if value, ok := _c.mutation.Prev(); ok {
		_spec.SetField(customitem.FieldPrev, field.TypeInt, value)
		_node.Prev = &value
	}
	if nodes := _c.mutation.VariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   customitem.VariantsTable,
			Columns: []string{customitem.VariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CustomItemCreateBulk is the builder for creating many CustomItem entities in bulk.
type CustomItemCreateBulk struct {
	config
	err      error
	builders []*CustomItemCreate
}

// Save creates the CustomItem entities in the database.
func (_c *CustomItemCreateBulk) Save(ctx context.Context) ([]*CustomItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomItemCreateBulk) SaveX(ctx context.Context) []*CustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
