// Code generated by ent, DO NOT EDIT.

package ent

// CreateItemInput represents a mutation input for creating items.
type CreateItemInput struct {
	Name    string
	Price   float64
	Image   string
	InStock bool
	Notes   string
}

// Mutate applies the CreateItemInput on the ItemMutation builder.
func (i *CreateItemInput) Mutate(m *ItemMutation) {
	m.SetName(i.Name)
	m.SetPrice(i.Price)
	m.SetImage(i.Image)
	m.SetInStock(i.InStock)
	m.SetNotes(i.Notes)
}

// SetInput applies the change-set in the CreateItemInput on the ItemCreate builder.
func (c *ItemCreate) SetInput(i CreateItemInput) *ItemCreate {
	i.Mutate(c.Mutation())
	return c
}

// UpdateItemInput represents a mutation input for updating items.
type UpdateItemInput struct {
	Name    *string
	Price   *float64
	Image   *string
	InStock *bool
	Notes   *string
}

// Mutate applies the UpdateItemInput on the ItemMutation builder.
func (i *UpdateItemInput) Mutate(m *ItemMutation) {
	if v := i.Name; v != nil {
		m.SetName(*v)
	}
	if v := i.Price; v != nil {
		m.SetPrice(*v)
	}
	if v := i.Image; v != nil {
		m.SetImage(*v)
	}
	if v := i.InStock; v != nil {
		m.SetInStock(*v)
	}
	if v := i.Notes; v != nil {
		m.SetNotes(*v)
	}
}

// SetInput applies the change-set in the UpdateItemInput on the ItemUpdate builder.
func (c *ItemUpdate) SetInput(i UpdateItemInput) *ItemUpdate {
	i.Mutate(c.Mutation())
	return c
}

// SetInput applies the change-set in the UpdateItemInput on the ItemUpdateOne builder.
func (c *ItemUpdateOne) SetInput(i UpdateItemInput) *ItemUpdateOne {
	i.Mutate(c.Mutation())
	return c
}
