// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/contrib/entgql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/orderitem"
)

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *CustomItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*CustomItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *CustomItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(customitem.Columns))
		selectedFields = []string{customitem.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "variants":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, itemImplementors)...); err != nil {
				return err
			}
			_q.WithNamedVariants(alias, func(wq *ItemQuery) {
				*wq = *query
			})
		case "name":
			if _, ok := fieldSeen[customitem.FieldName]; !ok {
				selectedFields = append(selectedFields, customitem.FieldName)
				fieldSeen[customitem.FieldName] = struct{}{}
			}
		case "allowOnlyOne":
			if _, ok := fieldSeen[customitem.FieldAllowOnlyOne]; !ok {
				selectedFields = append(selectedFields, customitem.FieldAllowOnlyOne)
				fieldSeen[customitem.FieldAllowOnlyOne] = struct{}{}
			}
		case "prev":
			if _, ok := fieldSeen[customitem.FieldPrev]; !ok {
				selectedFields = append(selectedFields, customitem.FieldPrev)
				fieldSeen[customitem.FieldPrev] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type customitemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []CustomItemPaginateOption
}

func newCustomItemPaginateArgs(rv map[string]any) *customitemPaginateArgs {
	args := &customitemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *ItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*ItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *ItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(item.Columns))
		selectedFields = []string{item.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {
		case "name":
			if _, ok := fieldSeen[item.FieldName]; !ok {
				selectedFields = append(selectedFields, item.FieldName)
				fieldSeen[item.FieldName] = struct{}{}
			}
		case "price":
			if _, ok := fieldSeen[item.FieldPrice]; !ok {
				selectedFields = append(selectedFields, item.FieldPrice)
				fieldSeen[item.FieldPrice] = struct{}{}
			}
		case "image":
			if _, ok := fieldSeen[item.FieldImage]; !ok {
				selectedFields = append(selectedFields, item.FieldImage)
				fieldSeen[item.FieldImage] = struct{}{}
			}
		case "inStock":
			if _, ok := fieldSeen[item.FieldInStock]; !ok {
				selectedFields = append(selectedFields, item.FieldInStock)
				fieldSeen[item.FieldInStock] = struct{}{}
			}
		case "notes":
			if _, ok := fieldSeen[item.FieldNotes]; !ok {
				selectedFields = append(selectedFields, item.FieldNotes)
				fieldSeen[item.FieldNotes] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type itemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []ItemPaginateOption
}

func newItemPaginateArgs(rv map[string]any) *itemPaginateArgs {
	args := &itemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OrderQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrderQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OrderQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(order.Columns))
		selectedFields = []string{order.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "items":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, orderitemImplementors)...); err != nil {
				return err
			}
			_q.WithNamedItems(alias, func(wq *OrderItemQuery) {
				*wq = *query
			})

		case "customItems":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderCustomItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, ordercustomitemImplementors)...); err != nil {
				return err
			}
			_q.WithNamedCustomItems(alias, func(wq *OrderCustomItemQuery) {
				*wq = *query
			})
		case "submitted":
			if _, ok := fieldSeen[order.FieldSubmitted]; !ok {
				selectedFields = append(selectedFields, order.FieldSubmitted)
				fieldSeen[order.FieldSubmitted] = struct{}{}
			}
		case "identifier":
			if _, ok := fieldSeen[order.FieldIdentifier]; !ok {
				selectedFields = append(selectedFields, order.FieldIdentifier)
				fieldSeen[order.FieldIdentifier] = struct{}{}
			}
		case "state":
			if _, ok := fieldSeen[order.FieldState]; !ok {
				selectedFields = append(selectedFields, order.FieldState)
				fieldSeen[order.FieldState] = struct{}{}
			}
		case "total":
			if _, ok := fieldSeen[order.FieldTotal]; !ok {
				selectedFields = append(selectedFields, order.FieldTotal)
				fieldSeen[order.FieldTotal] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type orderPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrderPaginateOption
}

func newOrderPaginateArgs(rv map[string]any) *orderPaginateArgs {
	args := &orderPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	if v, ok := rv[orderByField]; ok {
		switch v := v.(type) {
		case map[string]any:
			var (
				err1, err2 error
				order      = &OrderOrder{Field: &OrderOrderField{}, Direction: entgql.OrderDirectionAsc}
			)
			if d, ok := v[directionField]; ok {
				err1 = order.Direction.UnmarshalGQL(d)
			}
			if f, ok := v[fieldField]; ok {
				err2 = order.Field.UnmarshalGQL(f)
			}
			if err1 == nil && err2 == nil {
				args.opts = append(args.opts, WithOrderOrder(order))
			}
		case *OrderOrder:
			if v != nil {
				args.opts = append(args.opts, WithOrderOrder(v))
			}
		}
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OrderCustomItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrderCustomItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OrderCustomItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(ordercustomitem.Columns))
		selectedFields = []string{ordercustomitem.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "selectedCustomItems":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&SelectedCustomItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, selectedcustomitemImplementors)...); err != nil {
				return err
			}
			_q.WithNamedSelectedCustomItems(alias, func(wq *SelectedCustomItemQuery) {
				*wq = *query
			})

		case "masterCustomItem":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CustomItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, customitemImplementors)...); err != nil {
				return err
			}
			_q.withMasterCustomItem = query

		case "order":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, orderImplementors)...); err != nil {
				return err
			}
			_q.withOrder = query
		case "quantity":
			if _, ok := fieldSeen[ordercustomitem.FieldQuantity]; !ok {
				selectedFields = append(selectedFields, ordercustomitem.FieldQuantity)
				fieldSeen[ordercustomitem.FieldQuantity] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type ordercustomitemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrderCustomItemPaginateOption
}

func newOrderCustomItemPaginateArgs(rv map[string]any) *ordercustomitemPaginateArgs {
	args := &ordercustomitemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *OrderItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*OrderItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *OrderItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	var (
		unknownSeen    bool
		fieldSeen      = make(map[string]struct{}, len(orderitem.Columns))
		selectedFields = []string{orderitem.FieldID}
	)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "item":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, itemImplementors)...); err != nil {
				return err
			}
			_q.withItem = query

		case "order":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&OrderClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, orderImplementors)...); err != nil {
				return err
			}
			_q.withOrder = query
		case "quantity":
			if _, ok := fieldSeen[orderitem.FieldQuantity]; !ok {
				selectedFields = append(selectedFields, orderitem.FieldQuantity)
				fieldSeen[orderitem.FieldQuantity] = struct{}{}
			}
		case "id":
		case "__typename":
		default:
			unknownSeen = true
		}
	}
	if !unknownSeen {
		_q.Select(selectedFields...)
	}
	return nil
}

type orderitemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []OrderItemPaginateOption
}

func newOrderItemPaginateArgs(rv map[string]any) *orderitemPaginateArgs {
	args := &orderitemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

// CollectFields tells the query-builder to eagerly load connected nodes by resolver context.
func (_q *SelectedCustomItemQuery) CollectFields(ctx context.Context, satisfies ...string) (*SelectedCustomItemQuery, error) {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return _q, nil
	}
	if err := _q.collectField(ctx, false, graphql.GetOperationContext(ctx), fc.Field, nil, satisfies...); err != nil {
		return nil, err
	}
	return _q, nil
}

func (_q *SelectedCustomItemQuery) collectField(ctx context.Context, oneNode bool, opCtx *graphql.OperationContext, collected graphql.CollectedField, path []string, satisfies ...string) error {
	path = append([]string(nil), path...)
	for _, field := range graphql.CollectFields(opCtx, collected.Selections, satisfies) {
		switch field.Name {

		case "selectedVariants":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&ItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, false, opCtx, field, path, mayAddCondition(satisfies, itemImplementors)...); err != nil {
				return err
			}
			_q.WithNamedSelectedVariants(alias, func(wq *ItemQuery) {
				*wq = *query
			})

		case "customItem":
			var (
				alias = field.Alias
				path  = append(path, alias)
				query = (&CustomItemClient{config: _q.config}).Query()
			)
			if err := query.collectField(ctx, oneNode, opCtx, field, path, mayAddCondition(satisfies, customitemImplementors)...); err != nil {
				return err
			}
			_q.withCustomItem = query
		}
	}
	return nil
}

type selectedcustomitemPaginateArgs struct {
	first, last   *int
	after, before *Cursor
	opts          []SelectedCustomItemPaginateOption
}

func newSelectedCustomItemPaginateArgs(rv map[string]any) *selectedcustomitemPaginateArgs {
	args := &selectedcustomitemPaginateArgs{}
	if rv == nil {
		return args
	}
	if v := rv[firstField]; v != nil {
		args.first = v.(*int)
	}
	if v := rv[lastField]; v != nil {
		args.last = v.(*int)
	}
	if v := rv[afterField]; v != nil {
		args.after = v.(*Cursor)
	}
	if v := rv[beforeField]; v != nil {
		args.before = v.(*Cursor)
	}
	return args
}

const (
	afterField     = "after"
	firstField     = "first"
	beforeField    = "before"
	lastField      = "last"
	orderByField   = "orderBy"
	directionField = "direction"
	fieldField     = "field"
	whereField     = "where"
)

func fieldArgs(ctx context.Context, whereInput any, path ...string) map[string]any {
	field := collectedField(ctx, path...)
	if field == nil || field.Arguments == nil {
		return nil
	}
	oc := graphql.GetOperationContext(ctx)
	args := field.ArgumentMap(oc.Variables)
	return unmarshalArgs(ctx, whereInput, args)
}

// unmarshalArgs allows extracting the field arguments from their raw representation.
func unmarshalArgs(ctx context.Context, whereInput any, args map[string]any) map[string]any {
	for _, k := range []string{firstField, lastField} {
		v, ok := args[k]
		if !ok || v == nil {
			continue
		}
		i, err := graphql.UnmarshalInt(v)
		if err == nil {
			args[k] = &i
		}
	}
	for _, k := range []string{beforeField, afterField} {
		v, ok := args[k]
		if !ok {
			continue
		}
		c := &Cursor{}
		if c.UnmarshalGQL(v) == nil {
			args[k] = c
		}
	}
	if v, ok := args[whereField]; ok && whereInput != nil {
		if err := graphql.UnmarshalInputFromContext(ctx, v, whereInput); err == nil {
			args[whereField] = whereInput
		}
	}

	return args
}

// mayAddCondition appends another type condition to the satisfies list
// if it does not exist in the list.
func mayAddCondition(satisfies []string, typeCond []string) []string {
Cond:
	for _, c := range typeCond {
		for _, s := range satisfies {
			if c == s {
				continue Cond
			}
		}
		satisfies = append(satisfies, c)
	}
	return satisfies
}
