// Code generated by ent, DO NOT EDIT.

package ent

// CreateCustomItemInput represents a mutation input for creating customitems.
type CreateCustomItemInput struct {
	Name       string
	Exclusive  bool
	Next       int
	VariantIDs []int
}

// Mutate applies the CreateCustomItemInput on the CustomItemMutation builder.
func (i *CreateCustomItemInput) Mutate(m *CustomItemMutation) {
	m.SetName(i.Name)
	m.SetExclusive(i.Exclusive)
	m.SetNext(i.Next)
	if v := i.VariantIDs; len(v) > 0 {
		m.AddVariantIDs(v...)
	}
}

// SetInput applies the change-set in the CreateCustomItemInput on the CustomItemCreate builder.
func (c *CustomItemCreate) SetInput(i CreateCustomItemInput) *CustomItemCreate {
	i.Mutate(c.Mutation())
	return c
}
