// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/99designs/gqlgen/graphql"
)

func (_m *CustomItem) Variants(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedVariants(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.VariantsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryVariants().All(ctx)
	}
	return result, err
}

func (_m *Order) Items(ctx context.Context) (result []*OrderItem, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedItems(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.ItemsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryItems().All(ctx)
	}
	return result, err
}

func (_m *Order) CustomItems(ctx context.Context) (result []*OrderCustomItem, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedCustomItems(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.CustomItemsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QueryCustomItems().All(ctx)
	}
	return result, err
}

func (_m *OrderCustomItem) SelectedCustomItems(ctx context.Context) (result []*SelectedCustomItem, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSelectedCustomItems(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SelectedCustomItemsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySelectedCustomItems().All(ctx)
	}
	return result, err
}

func (_m *OrderCustomItem) MasterCustomItem(ctx context.Context) (*CustomItem, error) {
	result, err := _m.Edges.MasterCustomItemOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryMasterCustomItem().Only(ctx)
	}
	return result, err
}

func (_m *OrderItem) Item(ctx context.Context) (*Item, error) {
	result, err := _m.Edges.ItemOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryItem().Only(ctx)
	}
	return result, err
}

func (_m *SelectedCustomItem) SelectedVariants(ctx context.Context) (result []*Item, err error) {
	if fc := graphql.GetFieldContext(ctx); fc != nil && fc.Field.Alias != "" {
		result, err = _m.NamedSelectedVariants(graphql.GetFieldContext(ctx).Field.Alias)
	} else {
		result, err = _m.Edges.SelectedVariantsOrErr()
	}
	if IsNotLoaded(err) {
		result, err = _m.QuerySelectedVariants().All(ctx)
	}
	return result, err
}

func (_m *SelectedCustomItem) CustomItem(ctx context.Context) (*CustomItem, error) {
	result, err := _m.Edges.CustomItemOrErr()
	if IsNotLoaded(err) {
		result, err = _m.QueryCustomItem().Only(ctx)
	}
	return result, err
}
