// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codecrafter404/bubble/ent/item"
)

// Item is the model entity for the Item schema.
type Item struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// eg.: cheesecake
	Name string `json:"name,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// an url; eg.: https://example.com/cheesecake.png
	Image string `json:"image,omitempty"`
	// weather the item is (physically) in stock
	InStock bool `json:"in_stock,omitempty"`
	// Custom text, which will be displayed
	Notes string `json:"notes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ItemQuery when eager-loading is set.
	Edges                ItemEdges `json:"edges"`
	custom_item_variants *int
	selectValues         sql.SelectValues
}

// ItemEdges holds the relations/edges for other nodes in the graph.
type ItemEdges struct {
	// SelectedCustomItems holds the value of the selected_custom_items edge.
	SelectedCustomItems []*SelectedCustomItem `json:"selected_custom_items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool

	namedSelectedCustomItems map[string][]*SelectedCustomItem
}

// SelectedCustomItemsOrErr returns the SelectedCustomItems value or an error if the edge
// was not loaded in eager-loading.
func (e ItemEdges) SelectedCustomItemsOrErr() ([]*SelectedCustomItem, error) {
	if e.loadedTypes[0] {
		return e.SelectedCustomItems, nil
	}
	return nil, &NotLoadedError{edge: "selected_custom_items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Item) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case item.FieldInStock:
			values[i] = new(sql.NullBool)
		case item.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case item.FieldID:
			values[i] = new(sql.NullInt64)
		case item.FieldName, item.FieldImage, item.FieldNotes:
			values[i] = new(sql.NullString)
		case item.ForeignKeys[0]: // custom_item_variants
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Item fields.
func (_m *Item) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case item.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case item.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case item.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case item.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case item.FieldInStock:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field in_stock", values[i])
			} else if value.Valid {
				_m.InStock = value.Bool
			}
		case item.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case item.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field custom_item_variants", value)
			} else if value.Valid {
				_m.custom_item_variants = new(int)
				*_m.custom_item_variants = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Item.
// This includes values selected through modifiers, order, etc.
func (_m *Item) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySelectedCustomItems queries the "selected_custom_items" edge of the Item entity.
func (_m *Item) QuerySelectedCustomItems() *SelectedCustomItemQuery {
	return NewItemClient(_m.config).QuerySelectedCustomItems(_m)
}

// Update returns a builder for updating this Item.
// Note that you need to call Item.Unwrap() before calling this method if this Item
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Item) Update() *ItemUpdateOne {
	return NewItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Item entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Item) Unwrap() *Item {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Item is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Item) String() string {
	var builder strings.Builder
	builder.WriteString("Item(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("in_stock=")
	builder.WriteString(fmt.Sprintf("%v", _m.InStock))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteByte(')')
	return builder.String()
}

// NamedSelectedCustomItems returns the SelectedCustomItems named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *Item) NamedSelectedCustomItems(name string) ([]*SelectedCustomItem, error) {
	if _m.Edges.namedSelectedCustomItems == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSelectedCustomItems[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *Item) appendNamedSelectedCustomItems(name string, edges ...*SelectedCustomItem) {
	if _m.Edges.namedSelectedCustomItems == nil {
		_m.Edges.namedSelectedCustomItems = make(map[string][]*SelectedCustomItem)
	}
	if len(edges) == 0 {
		_m.Edges.namedSelectedCustomItems[name] = []*SelectedCustomItem{}
	} else {
		_m.Edges.namedSelectedCustomItems[name] = append(_m.Edges.namedSelectedCustomItems[name], edges...)
	}
}

// Items is a parsable slice of Item.
type Items []*Item
