// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/orderitem"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
}

// SetSubmitted sets the "submitted" field.
func (_c *OrderCreate) SetSubmitted(v time.Time) *OrderCreate {
	_c.mutation.SetSubmitted(v)
	return _c
}

// SetIdentifier sets the "identifier" field.
func (_c *OrderCreate) SetIdentifier(v string) *OrderCreate {
	_c.mutation.SetIdentifier(v)
	return _c
}

// SetState sets the "state" field.
func (_c *OrderCreate) SetState(v order.State) *OrderCreate {
	_c.mutation.SetState(v)
	return _c
}

// SetNillableState sets the "state" field if the given value is not nil.
func (_c *OrderCreate) SetNillableState(v *order.State) *OrderCreate {
	if v != nil {
		_c.SetState(*v)
	}
	return _c
}

// SetTotal sets the "total" field.
func (_c *OrderCreate) SetTotal(v float64) *OrderCreate {
	_c.mutation.SetTotal(v)
	return _c
}

// AddItemIDs adds the "items" edge to the OrderItem entity by IDs.
func (_c *OrderCreate) AddItemIDs(ids ...int) *OrderCreate {
	_c.mutation.AddItemIDs(ids...)
	return _c
}

// AddItems adds the "items" edges to the OrderItem entity.
func (_c *OrderCreate) AddItems(v ...*OrderItem) *OrderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddItemIDs(ids...)
}

// AddCustomItemIDs adds the "custom_items" edge to the OrderCustomItem entity by IDs.
func (_c *OrderCreate) AddCustomItemIDs(ids ...int) *OrderCreate {
	_c.mutation.AddCustomItemIDs(ids...)
	return _c
}

// AddCustomItems adds the "custom_items" edges to the OrderCustomItem entity.
func (_c *OrderCreate) AddCustomItems(v ...*OrderCustomItem) *OrderCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCustomItemIDs(ids...)
}

// Mutation returns the OrderMutation object of the builder.
func (_c *OrderCreate) Mutation() *OrderMutation {
	return _c.mutation
}

// Save creates the Order in the database.
func (_c *OrderCreate) Save(ctx context.Context) (*Order, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OrderCreate) defaults() {
	if _, ok := _c.mutation.State(); !ok {
		v := order.DefaultState
		_c.mutation.SetState(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCreate) check() error {
	if _, ok := _c.mutation.Submitted(); !ok {
		return &ValidationError{Name: "submitted", err: errors.New(`ent: missing required field "Order.submitted"`)}
	}
	if _, ok := _c.mutation.Identifier(); !ok {
		return &ValidationError{Name: "identifier", err: errors.New(`ent: missing required field "Order.identifier"`)}
	}
	if _, ok := _c.mutation.State(); !ok {
		return &ValidationError{Name: "state", err: errors.New(`ent: missing required field "Order.state"`)}
	}
	if v, ok := _c.mutation.State(); ok {
		if err := order.StateValidator(v); err != nil {
			return &ValidationError{Name: "state", err: fmt.Errorf(`ent: validator failed for field "Order.state": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Total(); !ok {
		return &ValidationError{Name: "total", err: errors.New(`ent: missing required field "Order.total"`)}
	}
	return nil
}

func (_c *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Submitted(); ok {
		_spec.SetField(order.FieldSubmitted, field.TypeTime, value)
		_node.Submitted = value
	}
	if value, ok := _c.mutation.Identifier(); ok {
		_spec.SetField(order.FieldIdentifier, field.TypeString, value)
		_node.Identifier = value
	}
	if value, ok := _c.mutation.State(); ok {
		_spec.SetField(order.FieldState, field.TypeEnum, value)
		_node.State = value
	}
	if value, ok := _c.mutation.Total(); ok {
		_spec.SetField(order.FieldTotal, field.TypeFloat64, value)
		_node.Total = value
	}
	if nodes := _c.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.ItemsTable,
			Columns: []string{order.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(orderitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   order.CustomItemsTable,
			Columns: []string{order.CustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(ordercustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
}

// Save creates the Order entities in the database.
func (_c *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Order, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
