// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// OrderCustomItemCreate is the builder for creating a OrderCustomItem entity.
type OrderCustomItemCreate struct {
	config
	mutation *OrderCustomItemMutation
	hooks    []Hook
}

// SetQuantity sets the "quantity" field.
func (_c *OrderCustomItemCreate) SetQuantity(v int) *OrderCustomItemCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// AddSelectedCustomItemIDs adds the "selected_custom_items" edge to the SelectedCustomItem entity by IDs.
func (_c *OrderCustomItemCreate) AddSelectedCustomItemIDs(ids ...int) *OrderCustomItemCreate {
	_c.mutation.AddSelectedCustomItemIDs(ids...)
	return _c
}

// AddSelectedCustomItems adds the "selected_custom_items" edges to the SelectedCustomItem entity.
func (_c *OrderCustomItemCreate) AddSelectedCustomItems(v ...*SelectedCustomItem) *OrderCustomItemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSelectedCustomItemIDs(ids...)
}

// SetMasterCustomItemID sets the "master_custom_item" edge to the CustomItem entity by ID.
func (_c *OrderCustomItemCreate) SetMasterCustomItemID(id int) *OrderCustomItemCreate {
	_c.mutation.SetMasterCustomItemID(id)
	return _c
}

// SetMasterCustomItem sets the "master_custom_item" edge to the CustomItem entity.
func (_c *OrderCustomItemCreate) SetMasterCustomItem(v *CustomItem) *OrderCustomItemCreate {
	return _c.SetMasterCustomItemID(v.ID)
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_c *OrderCustomItemCreate) SetOrderID(id int) *OrderCustomItemCreate {
	_c.mutation.SetOrderID(id)
	return _c
}

// SetNillableOrderID sets the "order" edge to the Order entity by ID if the given value is not nil.
func (_c *OrderCustomItemCreate) SetNillableOrderID(id *int) *OrderCustomItemCreate {
	if id != nil {
		_c = _c.SetOrderID(*id)
	}
	return _c
}

// SetOrder sets the "order" edge to the Order entity.
func (_c *OrderCustomItemCreate) SetOrder(v *Order) *OrderCustomItemCreate {
	return _c.SetOrderID(v.ID)
}

// Mutation returns the OrderCustomItemMutation object of the builder.
func (_c *OrderCustomItemCreate) Mutation() *OrderCustomItemMutation {
	return _c.mutation
}

// Save creates the OrderCustomItem in the database.
func (_c *OrderCustomItemCreate) Save(ctx context.Context) (*OrderCustomItem, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OrderCustomItemCreate) SaveX(ctx context.Context) *OrderCustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCustomItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCustomItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OrderCustomItemCreate) check() error {
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "OrderCustomItem.quantity"`)}
	}
	if len(_c.mutation.MasterCustomItemIDs()) == 0 {
		return &ValidationError{Name: "master_custom_item", err: errors.New(`ent: missing required edge "OrderCustomItem.master_custom_item"`)}
	}
	return nil
}

func (_c *OrderCustomItemCreate) sqlSave(ctx context.Context) (*OrderCustomItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OrderCustomItemCreate) createSpec() (*OrderCustomItem, *sqlgraph.CreateSpec) {
	var (
		_node = &OrderCustomItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(ordercustomitem.Table, sqlgraph.NewFieldSpec(ordercustomitem.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(ordercustomitem.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if nodes := _c.mutation.SelectedCustomItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MasterCustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ordercustomitem.MasterCustomItemTable,
			Columns: []string{ordercustomitem.MasterCustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_custom_item_master_custom_item = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercustomitem.OrderTable,
			Columns: []string{ordercustomitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.order_custom_items = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OrderCustomItemCreateBulk is the builder for creating many OrderCustomItem entities in bulk.
type OrderCustomItemCreateBulk struct {
	config
	err      error
	builders []*OrderCustomItemCreate
}

// Save creates the OrderCustomItem entities in the database.
func (_c *OrderCustomItemCreateBulk) Save(ctx context.Context) ([]*OrderCustomItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OrderCustomItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderCustomItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OrderCustomItemCreateBulk) SaveX(ctx context.Context) []*OrderCustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OrderCustomItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OrderCustomItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
