// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
)

// OrderCustomItem is the model entity for the OrderCustomItem schema.
type OrderCustomItem struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Quantity holds the value of the "quantity" field.
	Quantity int `json:"quantity,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OrderCustomItemQuery when eager-loading is set.
	Edges                                OrderCustomItemEdges `json:"edges"`
	order_custom_items                   *int
	order_custom_item_master_custom_item *int
	selectValues                         sql.SelectValues
}

// OrderCustomItemEdges holds the relations/edges for other nodes in the graph.
type OrderCustomItemEdges struct {
	// SelectedCustomItems holds the value of the selected_custom_items edge.
	SelectedCustomItems []*SelectedCustomItem `json:"selected_custom_items,omitempty"`
	// MasterCustomItem holds the value of the master_custom_item edge.
	MasterCustomItem *CustomItem `json:"master_custom_item,omitempty"`
	// Order holds the value of the order edge.
	Order *Order `json:"order,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
	// totalCount holds the count of the edges above.
	totalCount [3]map[string]int

	namedSelectedCustomItems map[string][]*SelectedCustomItem
}

// SelectedCustomItemsOrErr returns the SelectedCustomItems value or an error if the edge
// was not loaded in eager-loading.
func (e OrderCustomItemEdges) SelectedCustomItemsOrErr() ([]*SelectedCustomItem, error) {
	if e.loadedTypes[0] {
		return e.SelectedCustomItems, nil
	}
	return nil, &NotLoadedError{edge: "selected_custom_items"}
}

// MasterCustomItemOrErr returns the MasterCustomItem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderCustomItemEdges) MasterCustomItemOrErr() (*CustomItem, error) {
	if e.MasterCustomItem != nil {
		return e.MasterCustomItem, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: customitem.Label}
	}
	return nil, &NotLoadedError{edge: "master_custom_item"}
}

// OrderOrErr returns the Order value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OrderCustomItemEdges) OrderOrErr() (*Order, error) {
	if e.Order != nil {
		return e.Order, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: order.Label}
	}
	return nil, &NotLoadedError{edge: "order"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OrderCustomItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ordercustomitem.FieldID, ordercustomitem.FieldQuantity:
			values[i] = new(sql.NullInt64)
		case ordercustomitem.ForeignKeys[0]: // order_custom_items
			values[i] = new(sql.NullInt64)
		case ordercustomitem.ForeignKeys[1]: // order_custom_item_master_custom_item
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OrderCustomItem fields.
func (_m *OrderCustomItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ordercustomitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case ordercustomitem.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = int(value.Int64)
			}
		case ordercustomitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_custom_items", value)
			} else if value.Valid {
				_m.order_custom_items = new(int)
				*_m.order_custom_items = int(value.Int64)
			}
		case ordercustomitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_custom_item_master_custom_item", value)
			} else if value.Valid {
				_m.order_custom_item_master_custom_item = new(int)
				*_m.order_custom_item_master_custom_item = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OrderCustomItem.
// This includes values selected through modifiers, order, etc.
func (_m *OrderCustomItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySelectedCustomItems queries the "selected_custom_items" edge of the OrderCustomItem entity.
func (_m *OrderCustomItem) QuerySelectedCustomItems() *SelectedCustomItemQuery {
	return NewOrderCustomItemClient(_m.config).QuerySelectedCustomItems(_m)
}

// QueryMasterCustomItem queries the "master_custom_item" edge of the OrderCustomItem entity.
func (_m *OrderCustomItem) QueryMasterCustomItem() *CustomItemQuery {
	return NewOrderCustomItemClient(_m.config).QueryMasterCustomItem(_m)
}

// QueryOrder queries the "order" edge of the OrderCustomItem entity.
func (_m *OrderCustomItem) QueryOrder() *OrderQuery {
	return NewOrderCustomItemClient(_m.config).QueryOrder(_m)
}

// Update returns a builder for updating this OrderCustomItem.
// Note that you need to call OrderCustomItem.Unwrap() before calling this method if this OrderCustomItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OrderCustomItem) Update() *OrderCustomItemUpdateOne {
	return NewOrderCustomItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OrderCustomItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OrderCustomItem) Unwrap() *OrderCustomItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OrderCustomItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OrderCustomItem) String() string {
	var builder strings.Builder
	builder.WriteString("OrderCustomItem(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteByte(')')
	return builder.String()
}

// NamedSelectedCustomItems returns the SelectedCustomItems named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *OrderCustomItem) NamedSelectedCustomItems(name string) ([]*SelectedCustomItem, error) {
	if _m.Edges.namedSelectedCustomItems == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSelectedCustomItems[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *OrderCustomItem) appendNamedSelectedCustomItems(name string, edges ...*SelectedCustomItem) {
	if _m.Edges.namedSelectedCustomItems == nil {
		_m.Edges.namedSelectedCustomItems = make(map[string][]*SelectedCustomItem)
	}
	if len(edges) == 0 {
		_m.Edges.namedSelectedCustomItems[name] = []*SelectedCustomItem{}
	} else {
		_m.Edges.namedSelectedCustomItems[name] = append(_m.Edges.namedSelectedCustomItems[name], edges...)
	}
}

// OrderCustomItems is a parsable slice of OrderCustomItem.
type OrderCustomItems []*OrderCustomItem
