// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/predicate"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// OrderCustomItemUpdate is the builder for updating OrderCustomItem entities.
type OrderCustomItemUpdate struct {
	config
	hooks    []Hook
	mutation *OrderCustomItemMutation
}

// Where appends a list predicates to the OrderCustomItemUpdate builder.
func (_u *OrderCustomItemUpdate) Where(ps ...predicate.OrderCustomItem) *OrderCustomItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQuantity sets the "quantity" field.
func (_u *OrderCustomItemUpdate) SetQuantity(v int) *OrderCustomItemUpdate {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderCustomItemUpdate) SetNillableQuantity(v *int) *OrderCustomItemUpdate {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderCustomItemUpdate) AddQuantity(v int) *OrderCustomItemUpdate {
	_u.mutation.AddQuantity(v)
	return _u
}

// AddSelectedCustomItemIDs adds the "selected_custom_items" edge to the SelectedCustomItem entity by IDs.
func (_u *OrderCustomItemUpdate) AddSelectedCustomItemIDs(ids ...int) *OrderCustomItemUpdate {
	_u.mutation.AddSelectedCustomItemIDs(ids...)
	return _u
}

// AddSelectedCustomItems adds the "selected_custom_items" edges to the SelectedCustomItem entity.
func (_u *OrderCustomItemUpdate) AddSelectedCustomItems(v ...*SelectedCustomItem) *OrderCustomItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedCustomItemIDs(ids...)
}

// SetMasterCustomItemID sets the "master_custom_item" edge to the CustomItem entity by ID.
func (_u *OrderCustomItemUpdate) SetMasterCustomItemID(id int) *OrderCustomItemUpdate {
	_u.mutation.SetMasterCustomItemID(id)
	return _u
}

// SetNillableMasterCustomItemID sets the "master_custom_item" edge to the CustomItem entity by ID if the given value is not nil.
func (_u *OrderCustomItemUpdate) SetNillableMasterCustomItemID(id *int) *OrderCustomItemUpdate {
	if id != nil {
		_u = _u.SetMasterCustomItemID(*id)
	}
	return _u
}

// SetMasterCustomItem sets the "master_custom_item" edge to the CustomItem entity.
func (_u *OrderCustomItemUpdate) SetMasterCustomItem(v *CustomItem) *OrderCustomItemUpdate {
	return _u.SetMasterCustomItemID(v.ID)
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *OrderCustomItemUpdate) SetOrderID(id int) *OrderCustomItemUpdate {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetNillableOrderID sets the "order" edge to the Order entity by ID if the given value is not nil.
func (_u *OrderCustomItemUpdate) SetNillableOrderID(id *int) *OrderCustomItemUpdate {
	if id != nil {
		_u = _u.SetOrderID(*id)
	}
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderCustomItemUpdate) SetOrder(v *Order) *OrderCustomItemUpdate {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderCustomItemMutation object of the builder.
func (_u *OrderCustomItemUpdate) Mutation() *OrderCustomItemMutation {
	return _u.mutation
}

// ClearSelectedCustomItems clears all "selected_custom_items" edges to the SelectedCustomItem entity.
func (_u *OrderCustomItemUpdate) ClearSelectedCustomItems() *OrderCustomItemUpdate {
	_u.mutation.ClearSelectedCustomItems()
	return _u
}

// RemoveSelectedCustomItemIDs removes the "selected_custom_items" edge to SelectedCustomItem entities by IDs.
func (_u *OrderCustomItemUpdate) RemoveSelectedCustomItemIDs(ids ...int) *OrderCustomItemUpdate {
	_u.mutation.RemoveSelectedCustomItemIDs(ids...)
	return _u
}

// RemoveSelectedCustomItems removes "selected_custom_items" edges to SelectedCustomItem entities.
func (_u *OrderCustomItemUpdate) RemoveSelectedCustomItems(v ...*SelectedCustomItem) *OrderCustomItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedCustomItemIDs(ids...)
}

// ClearMasterCustomItem clears the "master_custom_item" edge to the CustomItem entity.
func (_u *OrderCustomItemUpdate) ClearMasterCustomItem() *OrderCustomItemUpdate {
	_u.mutation.ClearMasterCustomItem()
	return _u
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderCustomItemUpdate) ClearOrder() *OrderCustomItemUpdate {
	_u.mutation.ClearOrder()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrderCustomItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderCustomItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrderCustomItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderCustomItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrderCustomItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(ordercustomitem.Table, ordercustomitem.Columns, sqlgraph.NewFieldSpec(ordercustomitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(ordercustomitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(ordercustomitem.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.SelectedCustomItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedCustomItemsIDs(); len(nodes) > 0 && !_u.mutation.SelectedCustomItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedCustomItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MasterCustomItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ordercustomitem.MasterCustomItemTable,
			Columns: []string{ordercustomitem.MasterCustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MasterCustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ordercustomitem.MasterCustomItemTable,
			Columns: []string{ordercustomitem.MasterCustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercustomitem.OrderTable,
			Columns: []string{ordercustomitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercustomitem.OrderTable,
			Columns: []string{ordercustomitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ordercustomitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrderCustomItemUpdateOne is the builder for updating a single OrderCustomItem entity.
type OrderCustomItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderCustomItemMutation
}

// SetQuantity sets the "quantity" field.
func (_u *OrderCustomItemUpdateOne) SetQuantity(v int) *OrderCustomItemUpdateOne {
	_u.mutation.ResetQuantity()
	_u.mutation.SetQuantity(v)
	return _u
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (_u *OrderCustomItemUpdateOne) SetNillableQuantity(v *int) *OrderCustomItemUpdateOne {
	if v != nil {
		_u.SetQuantity(*v)
	}
	return _u
}

// AddQuantity adds value to the "quantity" field.
func (_u *OrderCustomItemUpdateOne) AddQuantity(v int) *OrderCustomItemUpdateOne {
	_u.mutation.AddQuantity(v)
	return _u
}

// AddSelectedCustomItemIDs adds the "selected_custom_items" edge to the SelectedCustomItem entity by IDs.
func (_u *OrderCustomItemUpdateOne) AddSelectedCustomItemIDs(ids ...int) *OrderCustomItemUpdateOne {
	_u.mutation.AddSelectedCustomItemIDs(ids...)
	return _u
}

// AddSelectedCustomItems adds the "selected_custom_items" edges to the SelectedCustomItem entity.
func (_u *OrderCustomItemUpdateOne) AddSelectedCustomItems(v ...*SelectedCustomItem) *OrderCustomItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedCustomItemIDs(ids...)
}

// SetMasterCustomItemID sets the "master_custom_item" edge to the CustomItem entity by ID.
func (_u *OrderCustomItemUpdateOne) SetMasterCustomItemID(id int) *OrderCustomItemUpdateOne {
	_u.mutation.SetMasterCustomItemID(id)
	return _u
}

// SetNillableMasterCustomItemID sets the "master_custom_item" edge to the CustomItem entity by ID if the given value is not nil.
func (_u *OrderCustomItemUpdateOne) SetNillableMasterCustomItemID(id *int) *OrderCustomItemUpdateOne {
	if id != nil {
		_u = _u.SetMasterCustomItemID(*id)
	}
	return _u
}

// SetMasterCustomItem sets the "master_custom_item" edge to the CustomItem entity.
func (_u *OrderCustomItemUpdateOne) SetMasterCustomItem(v *CustomItem) *OrderCustomItemUpdateOne {
	return _u.SetMasterCustomItemID(v.ID)
}

// SetOrderID sets the "order" edge to the Order entity by ID.
func (_u *OrderCustomItemUpdateOne) SetOrderID(id int) *OrderCustomItemUpdateOne {
	_u.mutation.SetOrderID(id)
	return _u
}

// SetNillableOrderID sets the "order" edge to the Order entity by ID if the given value is not nil.
func (_u *OrderCustomItemUpdateOne) SetNillableOrderID(id *int) *OrderCustomItemUpdateOne {
	if id != nil {
		_u = _u.SetOrderID(*id)
	}
	return _u
}

// SetOrder sets the "order" edge to the Order entity.
func (_u *OrderCustomItemUpdateOne) SetOrder(v *Order) *OrderCustomItemUpdateOne {
	return _u.SetOrderID(v.ID)
}

// Mutation returns the OrderCustomItemMutation object of the builder.
func (_u *OrderCustomItemUpdateOne) Mutation() *OrderCustomItemMutation {
	return _u.mutation
}

// ClearSelectedCustomItems clears all "selected_custom_items" edges to the SelectedCustomItem entity.
func (_u *OrderCustomItemUpdateOne) ClearSelectedCustomItems() *OrderCustomItemUpdateOne {
	_u.mutation.ClearSelectedCustomItems()
	return _u
}

// RemoveSelectedCustomItemIDs removes the "selected_custom_items" edge to SelectedCustomItem entities by IDs.
func (_u *OrderCustomItemUpdateOne) RemoveSelectedCustomItemIDs(ids ...int) *OrderCustomItemUpdateOne {
	_u.mutation.RemoveSelectedCustomItemIDs(ids...)
	return _u
}

// RemoveSelectedCustomItems removes "selected_custom_items" edges to SelectedCustomItem entities.
func (_u *OrderCustomItemUpdateOne) RemoveSelectedCustomItems(v ...*SelectedCustomItem) *OrderCustomItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedCustomItemIDs(ids...)
}

// ClearMasterCustomItem clears the "master_custom_item" edge to the CustomItem entity.
func (_u *OrderCustomItemUpdateOne) ClearMasterCustomItem() *OrderCustomItemUpdateOne {
	_u.mutation.ClearMasterCustomItem()
	return _u
}

// ClearOrder clears the "order" edge to the Order entity.
func (_u *OrderCustomItemUpdateOne) ClearOrder() *OrderCustomItemUpdateOne {
	_u.mutation.ClearOrder()
	return _u
}

// Where appends a list predicates to the OrderCustomItemUpdate builder.
func (_u *OrderCustomItemUpdateOne) Where(ps ...predicate.OrderCustomItem) *OrderCustomItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrderCustomItemUpdateOne) Select(field string, fields ...string) *OrderCustomItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OrderCustomItem entity.
func (_u *OrderCustomItemUpdateOne) Save(ctx context.Context) (*OrderCustomItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrderCustomItemUpdateOne) SaveX(ctx context.Context) *OrderCustomItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrderCustomItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrderCustomItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *OrderCustomItemUpdateOne) sqlSave(ctx context.Context) (_node *OrderCustomItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(ordercustomitem.Table, ordercustomitem.Columns, sqlgraph.NewFieldSpec(ordercustomitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OrderCustomItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ordercustomitem.FieldID)
		for _, f := range fields {
			if !ordercustomitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ordercustomitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Quantity(); ok {
		_spec.SetField(ordercustomitem.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedQuantity(); ok {
		_spec.AddField(ordercustomitem.FieldQuantity, field.TypeInt, value)
	}
	if _u.mutation.SelectedCustomItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedCustomItemsIDs(); len(nodes) > 0 && !_u.mutation.SelectedCustomItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedCustomItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   ordercustomitem.SelectedCustomItemsTable,
			Columns: []string{ordercustomitem.SelectedCustomItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.MasterCustomItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ordercustomitem.MasterCustomItemTable,
			Columns: []string{ordercustomitem.MasterCustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MasterCustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   ordercustomitem.MasterCustomItemTable,
			Columns: []string{ordercustomitem.MasterCustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.OrderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercustomitem.OrderTable,
			Columns: []string{ordercustomitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OrderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   ordercustomitem.OrderTable,
			Columns: []string{ordercustomitem.OrderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OrderCustomItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ordercustomitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
