// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/codecrafter404/bubble/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	orderFields := schema.Order{}.Fields()
	_ = orderFields
}
