// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// SelectedCustomItemCreate is the builder for creating a SelectedCustomItem entity.
type SelectedCustomItemCreate struct {
	config
	mutation *SelectedCustomItemMutation
	hooks    []Hook
}

// AddSelectedVariantIDs adds the "selected_variants" edge to the Item entity by IDs.
func (_c *SelectedCustomItemCreate) AddSelectedVariantIDs(ids ...int) *SelectedCustomItemCreate {
	_c.mutation.AddSelectedVariantIDs(ids...)
	return _c
}

// AddSelectedVariants adds the "selected_variants" edges to the Item entity.
func (_c *SelectedCustomItemCreate) AddSelectedVariants(v ...*Item) *SelectedCustomItemCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSelectedVariantIDs(ids...)
}

// SetCustomItemID sets the "custom_item" edge to the CustomItem entity by ID.
func (_c *SelectedCustomItemCreate) SetCustomItemID(id int) *SelectedCustomItemCreate {
	_c.mutation.SetCustomItemID(id)
	return _c
}

// SetCustomItem sets the "custom_item" edge to the CustomItem entity.
func (_c *SelectedCustomItemCreate) SetCustomItem(v *CustomItem) *SelectedCustomItemCreate {
	return _c.SetCustomItemID(v.ID)
}

// Mutation returns the SelectedCustomItemMutation object of the builder.
func (_c *SelectedCustomItemCreate) Mutation() *SelectedCustomItemMutation {
	return _c.mutation
}

// Save creates the SelectedCustomItem in the database.
func (_c *SelectedCustomItemCreate) Save(ctx context.Context) (*SelectedCustomItem, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SelectedCustomItemCreate) SaveX(ctx context.Context) *SelectedCustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelectedCustomItemCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelectedCustomItemCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SelectedCustomItemCreate) check() error {
	if len(_c.mutation.SelectedVariantsIDs()) == 0 {
		return &ValidationError{Name: "selected_variants", err: errors.New(`ent: missing required edge "SelectedCustomItem.selected_variants"`)}
	}
	if len(_c.mutation.CustomItemIDs()) == 0 {
		return &ValidationError{Name: "custom_item", err: errors.New(`ent: missing required edge "SelectedCustomItem.custom_item"`)}
	}
	return nil
}

func (_c *SelectedCustomItemCreate) sqlSave(ctx context.Context) (*SelectedCustomItem, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SelectedCustomItemCreate) createSpec() (*SelectedCustomItem, *sqlgraph.CreateSpec) {
	var (
		_node = &SelectedCustomItem{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(selectedcustomitem.Table, sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt))
	)
	if nodes := _c.mutation.SelectedVariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: selectedcustomitem.SelectedVariantsPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   selectedcustomitem.CustomItemTable,
			Columns: []string{selectedcustomitem.CustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.selected_custom_item_custom_item = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SelectedCustomItemCreateBulk is the builder for creating many SelectedCustomItem entities in bulk.
type SelectedCustomItemCreateBulk struct {
	config
	err      error
	builders []*SelectedCustomItemCreate
}

// Save creates the SelectedCustomItem entities in the database.
func (_c *SelectedCustomItemCreateBulk) Save(ctx context.Context) ([]*SelectedCustomItem, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SelectedCustomItem, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SelectedCustomItemMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SelectedCustomItemCreateBulk) SaveX(ctx context.Context) []*SelectedCustomItem {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SelectedCustomItemCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SelectedCustomItemCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
