// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// SelectedCustomItem is the model entity for the SelectedCustomItem schema.
type SelectedCustomItem struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SelectedCustomItemQuery when eager-loading is set.
	Edges                                   SelectedCustomItemEdges `json:"edges"`
	order_custom_item_selected_custom_items *int
	selected_custom_item_custom_item        *int
	selectValues                            sql.SelectValues
}

// SelectedCustomItemEdges holds the relations/edges for other nodes in the graph.
type SelectedCustomItemEdges struct {
	// SelectedVariants holds the value of the selected_variants edge.
	SelectedVariants []*Item `json:"selected_variants,omitempty"`
	// CustomItem holds the value of the custom_item edge.
	CustomItem *CustomItem `json:"custom_item,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedSelectedVariants map[string][]*Item
}

// SelectedVariantsOrErr returns the SelectedVariants value or an error if the edge
// was not loaded in eager-loading.
func (e SelectedCustomItemEdges) SelectedVariantsOrErr() ([]*Item, error) {
	if e.loadedTypes[0] {
		return e.SelectedVariants, nil
	}
	return nil, &NotLoadedError{edge: "selected_variants"}
}

// CustomItemOrErr returns the CustomItem value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SelectedCustomItemEdges) CustomItemOrErr() (*CustomItem, error) {
	if e.CustomItem != nil {
		return e.CustomItem, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: customitem.Label}
	}
	return nil, &NotLoadedError{edge: "custom_item"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SelectedCustomItem) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case selectedcustomitem.FieldID:
			values[i] = new(sql.NullInt64)
		case selectedcustomitem.ForeignKeys[0]: // order_custom_item_selected_custom_items
			values[i] = new(sql.NullInt64)
		case selectedcustomitem.ForeignKeys[1]: // selected_custom_item_custom_item
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SelectedCustomItem fields.
func (_m *SelectedCustomItem) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case selectedcustomitem.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case selectedcustomitem.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field order_custom_item_selected_custom_items", value)
			} else if value.Valid {
				_m.order_custom_item_selected_custom_items = new(int)
				*_m.order_custom_item_selected_custom_items = int(value.Int64)
			}
		case selectedcustomitem.ForeignKeys[1]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field selected_custom_item_custom_item", value)
			} else if value.Valid {
				_m.selected_custom_item_custom_item = new(int)
				*_m.selected_custom_item_custom_item = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SelectedCustomItem.
// This includes values selected through modifiers, order, etc.
func (_m *SelectedCustomItem) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySelectedVariants queries the "selected_variants" edge of the SelectedCustomItem entity.
func (_m *SelectedCustomItem) QuerySelectedVariants() *ItemQuery {
	return NewSelectedCustomItemClient(_m.config).QuerySelectedVariants(_m)
}

// QueryCustomItem queries the "custom_item" edge of the SelectedCustomItem entity.
func (_m *SelectedCustomItem) QueryCustomItem() *CustomItemQuery {
	return NewSelectedCustomItemClient(_m.config).QueryCustomItem(_m)
}

// Update returns a builder for updating this SelectedCustomItem.
// Note that you need to call SelectedCustomItem.Unwrap() before calling this method if this SelectedCustomItem
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SelectedCustomItem) Update() *SelectedCustomItemUpdateOne {
	return NewSelectedCustomItemClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SelectedCustomItem entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SelectedCustomItem) Unwrap() *SelectedCustomItem {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SelectedCustomItem is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SelectedCustomItem) String() string {
	var builder strings.Builder
	builder.WriteString("SelectedCustomItem(")
	builder.WriteString(fmt.Sprintf("id=%v", _m.ID))
	builder.WriteByte(')')
	return builder.String()
}

// NamedSelectedVariants returns the SelectedVariants named value or an error if the edge was not
// loaded in eager-loading with this name.
func (_m *SelectedCustomItem) NamedSelectedVariants(name string) ([]*Item, error) {
	if _m.Edges.namedSelectedVariants == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := _m.Edges.namedSelectedVariants[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (_m *SelectedCustomItem) appendNamedSelectedVariants(name string, edges ...*Item) {
	if _m.Edges.namedSelectedVariants == nil {
		_m.Edges.namedSelectedVariants = make(map[string][]*Item)
	}
	if len(edges) == 0 {
		_m.Edges.namedSelectedVariants[name] = []*Item{}
	} else {
		_m.Edges.namedSelectedVariants[name] = append(_m.Edges.namedSelectedVariants[name], edges...)
	}
}

// SelectedCustomItems is a parsable slice of SelectedCustomItem.
type SelectedCustomItems []*SelectedCustomItem
