// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
	"github.com/codecrafter404/bubble/ent/predicate"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// SelectedCustomItemUpdate is the builder for updating SelectedCustomItem entities.
type SelectedCustomItemUpdate struct {
	config
	hooks    []Hook
	mutation *SelectedCustomItemMutation
}

// Where appends a list predicates to the SelectedCustomItemUpdate builder.
func (_u *SelectedCustomItemUpdate) Where(ps ...predicate.SelectedCustomItem) *SelectedCustomItemUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// AddSelectedVariantIDs adds the "selected_variants" edge to the Item entity by IDs.
func (_u *SelectedCustomItemUpdate) AddSelectedVariantIDs(ids ...int) *SelectedCustomItemUpdate {
	_u.mutation.AddSelectedVariantIDs(ids...)
	return _u
}

// AddSelectedVariants adds the "selected_variants" edges to the Item entity.
func (_u *SelectedCustomItemUpdate) AddSelectedVariants(v ...*Item) *SelectedCustomItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedVariantIDs(ids...)
}

// SetCustomItemID sets the "custom_item" edge to the CustomItem entity by ID.
func (_u *SelectedCustomItemUpdate) SetCustomItemID(id int) *SelectedCustomItemUpdate {
	_u.mutation.SetCustomItemID(id)
	return _u
}

// SetNillableCustomItemID sets the "custom_item" edge to the CustomItem entity by ID if the given value is not nil.
func (_u *SelectedCustomItemUpdate) SetNillableCustomItemID(id *int) *SelectedCustomItemUpdate {
	if id != nil {
		_u = _u.SetCustomItemID(*id)
	}
	return _u
}

// SetCustomItem sets the "custom_item" edge to the CustomItem entity.
func (_u *SelectedCustomItemUpdate) SetCustomItem(v *CustomItem) *SelectedCustomItemUpdate {
	return _u.SetCustomItemID(v.ID)
}

// Mutation returns the SelectedCustomItemMutation object of the builder.
func (_u *SelectedCustomItemUpdate) Mutation() *SelectedCustomItemMutation {
	return _u.mutation
}

// ClearSelectedVariants clears all "selected_variants" edges to the Item entity.
func (_u *SelectedCustomItemUpdate) ClearSelectedVariants() *SelectedCustomItemUpdate {
	_u.mutation.ClearSelectedVariants()
	return _u
}

// RemoveSelectedVariantIDs removes the "selected_variants" edge to Item entities by IDs.
func (_u *SelectedCustomItemUpdate) RemoveSelectedVariantIDs(ids ...int) *SelectedCustomItemUpdate {
	_u.mutation.RemoveSelectedVariantIDs(ids...)
	return _u
}

// RemoveSelectedVariants removes "selected_variants" edges to Item entities.
func (_u *SelectedCustomItemUpdate) RemoveSelectedVariants(v ...*Item) *SelectedCustomItemUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedVariantIDs(ids...)
}

// ClearCustomItem clears the "custom_item" edge to the CustomItem entity.
func (_u *SelectedCustomItemUpdate) ClearCustomItem() *SelectedCustomItemUpdate {
	_u.mutation.ClearCustomItem()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SelectedCustomItemUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SelectedCustomItemUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SelectedCustomItemUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SelectedCustomItemUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SelectedCustomItemUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(selectedcustomitem.Table, selectedcustomitem.Columns, sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SelectedVariantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedVariantsIDs(); len(nodes) > 0 && !_u.mutation.SelectedVariantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedVariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   selectedcustomitem.CustomItemTable,
			Columns: []string{selectedcustomitem.CustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   selectedcustomitem.CustomItemTable,
			Columns: []string{selectedcustomitem.CustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{selectedcustomitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SelectedCustomItemUpdateOne is the builder for updating a single SelectedCustomItem entity.
type SelectedCustomItemUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SelectedCustomItemMutation
}

// AddSelectedVariantIDs adds the "selected_variants" edge to the Item entity by IDs.
func (_u *SelectedCustomItemUpdateOne) AddSelectedVariantIDs(ids ...int) *SelectedCustomItemUpdateOne {
	_u.mutation.AddSelectedVariantIDs(ids...)
	return _u
}

// AddSelectedVariants adds the "selected_variants" edges to the Item entity.
func (_u *SelectedCustomItemUpdateOne) AddSelectedVariants(v ...*Item) *SelectedCustomItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSelectedVariantIDs(ids...)
}

// SetCustomItemID sets the "custom_item" edge to the CustomItem entity by ID.
func (_u *SelectedCustomItemUpdateOne) SetCustomItemID(id int) *SelectedCustomItemUpdateOne {
	_u.mutation.SetCustomItemID(id)
	return _u
}

// SetNillableCustomItemID sets the "custom_item" edge to the CustomItem entity by ID if the given value is not nil.
func (_u *SelectedCustomItemUpdateOne) SetNillableCustomItemID(id *int) *SelectedCustomItemUpdateOne {
	if id != nil {
		_u = _u.SetCustomItemID(*id)
	}
	return _u
}

// SetCustomItem sets the "custom_item" edge to the CustomItem entity.
func (_u *SelectedCustomItemUpdateOne) SetCustomItem(v *CustomItem) *SelectedCustomItemUpdateOne {
	return _u.SetCustomItemID(v.ID)
}

// Mutation returns the SelectedCustomItemMutation object of the builder.
func (_u *SelectedCustomItemUpdateOne) Mutation() *SelectedCustomItemMutation {
	return _u.mutation
}

// ClearSelectedVariants clears all "selected_variants" edges to the Item entity.
func (_u *SelectedCustomItemUpdateOne) ClearSelectedVariants() *SelectedCustomItemUpdateOne {
	_u.mutation.ClearSelectedVariants()
	return _u
}

// RemoveSelectedVariantIDs removes the "selected_variants" edge to Item entities by IDs.
func (_u *SelectedCustomItemUpdateOne) RemoveSelectedVariantIDs(ids ...int) *SelectedCustomItemUpdateOne {
	_u.mutation.RemoveSelectedVariantIDs(ids...)
	return _u
}

// RemoveSelectedVariants removes "selected_variants" edges to Item entities.
func (_u *SelectedCustomItemUpdateOne) RemoveSelectedVariants(v ...*Item) *SelectedCustomItemUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSelectedVariantIDs(ids...)
}

// ClearCustomItem clears the "custom_item" edge to the CustomItem entity.
func (_u *SelectedCustomItemUpdateOne) ClearCustomItem() *SelectedCustomItemUpdateOne {
	_u.mutation.ClearCustomItem()
	return _u
}

// Where appends a list predicates to the SelectedCustomItemUpdate builder.
func (_u *SelectedCustomItemUpdateOne) Where(ps ...predicate.SelectedCustomItem) *SelectedCustomItemUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SelectedCustomItemUpdateOne) Select(field string, fields ...string) *SelectedCustomItemUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SelectedCustomItem entity.
func (_u *SelectedCustomItemUpdateOne) Save(ctx context.Context) (*SelectedCustomItem, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SelectedCustomItemUpdateOne) SaveX(ctx context.Context) *SelectedCustomItem {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SelectedCustomItemUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SelectedCustomItemUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SelectedCustomItemUpdateOne) sqlSave(ctx context.Context) (_node *SelectedCustomItem, err error) {
	_spec := sqlgraph.NewUpdateSpec(selectedcustomitem.Table, selectedcustomitem.Columns, sqlgraph.NewFieldSpec(selectedcustomitem.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SelectedCustomItem.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, selectedcustomitem.FieldID)
		for _, f := range fields {
			if !selectedcustomitem.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != selectedcustomitem.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.SelectedVariantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSelectedVariantsIDs(); len(nodes) > 0 && !_u.mutation.SelectedVariantsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SelectedVariantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   selectedcustomitem.SelectedVariantsTable,
			Columns: []string{selectedcustomitem.SelectedVariantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(item.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CustomItemCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   selectedcustomitem.CustomItemTable,
			Columns: []string{selectedcustomitem.CustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomItemIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   selectedcustomitem.CustomItemTable,
			Columns: []string{selectedcustomitem.CustomItemColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customitem.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SelectedCustomItem{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{selectedcustomitem.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
