type Item {
  "should be unique across items/customitems"
  id: Int! @primary
  "eg.: cheesecake"
  name: String!
  price: Float!
  "an url eg.: https://example.com/cheesecake"
  image: String!
  "wheather the item is in stock; if all variants of a customitems are out of stock, the customitem will also go out of stock"
  available: Boolean!
  "custom text which will be displayed to the user underneath the name"
  identifier: String!
  "false if the item is a variant"
  isVariant: Boolean!
}

input UpdateItem {
  name: String
  price: Float
  image: String
  available: Boolean
  identifier: String
  isVariant: Boolean
}

input NewItem {
  id: Int!
  name: String!
  price: Float!
  image: String!
  available: Boolean!
  identifier: String!
  isVariant: Boolean!
}
