type OrderItem {
  quantity: Int!
  item: Item! @gorm(tags: "embedded") # in order to not lose historical price / variation data
}

input NewOrderItem {
  quantity: Int!
  itemId: Int!
}


type OrderCustomItem {
  quantity: Int!
  customItem: CustomItem! @gorm(tags: "embedded")
}

input NewOrderCustomItem {
  customItemId: Int!
  quantity: Int!
  variants: [Int!]!
}

enum OrderState {
  CREATED
  PENDING
  COMPLEATED
  CANCELED
}

type Order {
  id: Int! 
  "UNIX Timestamp"
  timestamp: Int64!
  "A string generated sequencially to identifiy an OPEN order"
  identifier: String!

  state: OrderState! @gorm(tags: "embedded")
  total: Float!

  items: [OrderItem!]! @gorm(tags: "foreignKey:Items;references:ID")
  customItems: [OrderCustomItem!]! @gorm(tags: "foreignKey:Items;references:ID")
}

input NewOrder {
  items: [NewOrderItem!]!
  customItems: [NewOrderCustomItem!]!
  "the total amount of money earned"
  total: Float!
}

