directive @gorm(
	tags: String
) on INPUT_FIELD_DEFINITION | FIELD_DEFINITION

directive @primary on INPUT_FIELD_DEFINITION | FIELD_DEFINITION


scalar Int64

enum User {
  ADMIN
  USER
}


type Statistics {
  totalOrders: Int!
  totalOrdersCompleated: Int!
  totalEarned: Float!
}

type Query {
  getPermission: User!
  getOrder(id: Int!): Order
  getItems: [Item!]!
  getCustomItems: [CustomItem!]!
}


type Mutation {
  createOrder(order: NewOrder!): Order!
  updateOrder(order: Int!, state: OrderState!): Order
  "Only available to admins"
  deleteOrder(order: Int!): Int!

  updateItem(id: Int!, item: UpdateItem!): Item!
  updateCustomItem(id: Int!, item: UpdateCustomItem!): CustomItem!

  createItems(items: [NewItem!]!): [Int!]!
  createCustomItems(items: [NewCustomItem!]!): [Int!]!
}


enum UpdateEvent {
  UPDATE_CUSTOMITEM
  UPDATE_ITEM
}

type Subscription {
  orders(state: OrderState, id: Int, limit: Int, skip: Int, sortAsc: Boolean): [Order!]!
  "The next order that should be worked on by the client"
  nextOrder: Order
  updates: UpdateEvent
  stats: Statistics!
}

schema {
  query: Query
  mutation: Mutation
  subscription: Subscription
}
