// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CustomItem is the predicate function for customitem builders.
type CustomItem func(*sql.Selector)

// Item is the predicate function for item builders.
type Item func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)

// OrderCustomItem is the predicate function for ordercustomitem builders.
type OrderCustomItem func(*sql.Selector)

// OrderItem is the predicate function for orderitem builders.
type OrderItem func(*sql.Selector)

// SelectedCustomItem is the predicate function for selectedcustomitem builders.
type SelectedCustomItem func(*sql.Selector)
