// Code generated by ent, DO NOT EDIT.

package selectedcustomitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codecrafter404/bubble/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.FieldLTE(FieldID, id))
}

// HasSelectedVariants applies the HasEdge predicate on the "selected_variants" edge.
func HasSelectedVariants() predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SelectedVariantsTable, SelectedVariantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSelectedVariantsWith applies the HasEdge predicate on the "selected_variants" edge with a given conditions (other predicates).
func HasSelectedVariantsWith(preds ...predicate.Item) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(func(s *sql.Selector) {
		step := newSelectedVariantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCustomItem applies the HasEdge predicate on the "custom_item" edge.
func HasCustomItem() predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, CustomItemTable, CustomItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomItemWith applies the HasEdge predicate on the "custom_item" edge with a given conditions (other predicates).
func HasCustomItemWith(preds ...predicate.CustomItem) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(func(s *sql.Selector) {
		step := newCustomItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SelectedCustomItem) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SelectedCustomItem) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SelectedCustomItem) predicate.SelectedCustomItem {
	return predicate.SelectedCustomItem(sql.NotPredicates(p))
}
