// Code generated by ent, DO NOT EDIT.

package customitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the customitem type in the database.
	Label = "custom_item"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAllowOnlyOne holds the string denoting the allow_only_one field in the database.
	FieldAllowOnlyOne = "allow_only_one"
	// FieldPrev holds the string denoting the prev field in the database.
	FieldPrev = "prev"
	// EdgeVariants holds the string denoting the variants edge name in mutations.
	EdgeVariants = "variants"
	// Table holds the table name of the customitem in the database.
	Table = "custom_items"
	// VariantsTable is the table that holds the variants relation/edge.
	VariantsTable = "items"
	// VariantsInverseTable is the table name for the Item entity.
	// It exists in this package in order to avoid circular dependency with the "item" package.
	VariantsInverseTable = "items"
	// VariantsColumn is the table column denoting the variants relation/edge.
	VariantsColumn = "custom_item_variants"
)

// Columns holds all SQL columns for customitem fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldAllowOnlyOne,
	FieldPrev,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the CustomItem queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAllowOnlyOne orders the results by the allow_only_one field.
func ByAllowOnlyOne(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowOnlyOne, opts...).ToFunc()
}

// ByPrev orders the results by the prev field.
func ByPrev(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrev, opts...).ToFunc()
}

// ByVariantsCount orders the results by variants count.
func ByVariantsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVariantsStep(), opts...)
	}
}

// ByVariants orders the results by variants terms.
func ByVariants(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVariantsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newVariantsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VariantsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, VariantsTable, VariantsColumn),
	)
}
