// Code generated by ent, DO NOT EDIT.

package customitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codecrafter404/bubble/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldName, v))
}

// AllowOnlyOne applies equality check predicate on the "allow_only_one" field. It's identical to AllowOnlyOneEQ.
func AllowOnlyOne(v bool) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldAllowOnlyOne, v))
}

// Prev applies equality check predicate on the "prev" field. It's identical to PrevEQ.
func Prev(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldPrev, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldContainsFold(FieldName, v))
}

// AllowOnlyOneEQ applies the EQ predicate on the "allow_only_one" field.
func AllowOnlyOneEQ(v bool) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldAllowOnlyOne, v))
}

// AllowOnlyOneNEQ applies the NEQ predicate on the "allow_only_one" field.
func AllowOnlyOneNEQ(v bool) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNEQ(FieldAllowOnlyOne, v))
}

// PrevEQ applies the EQ predicate on the "prev" field.
func PrevEQ(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldEQ(FieldPrev, v))
}

// PrevNEQ applies the NEQ predicate on the "prev" field.
func PrevNEQ(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNEQ(FieldPrev, v))
}

// PrevIn applies the In predicate on the "prev" field.
func PrevIn(vs ...int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldIn(FieldPrev, vs...))
}

// PrevNotIn applies the NotIn predicate on the "prev" field.
func PrevNotIn(vs ...int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNotIn(FieldPrev, vs...))
}

// PrevGT applies the GT predicate on the "prev" field.
func PrevGT(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGT(FieldPrev, v))
}

// PrevGTE applies the GTE predicate on the "prev" field.
func PrevGTE(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldGTE(FieldPrev, v))
}

// PrevLT applies the LT predicate on the "prev" field.
func PrevLT(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLT(FieldPrev, v))
}

// PrevLTE applies the LTE predicate on the "prev" field.
func PrevLTE(v int) predicate.CustomItem {
	return predicate.CustomItem(sql.FieldLTE(FieldPrev, v))
}

// PrevIsNil applies the IsNil predicate on the "prev" field.
func PrevIsNil() predicate.CustomItem {
	return predicate.CustomItem(sql.FieldIsNull(FieldPrev))
}

// PrevNotNil applies the NotNil predicate on the "prev" field.
func PrevNotNil() predicate.CustomItem {
	return predicate.CustomItem(sql.FieldNotNull(FieldPrev))
}

// HasVariants applies the HasEdge predicate on the "variants" edge.
func HasVariants() predicate.CustomItem {
	return predicate.CustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, VariantsTable, VariantsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVariantsWith applies the HasEdge predicate on the "variants" edge with a given conditions (other predicates).
func HasVariantsWith(preds ...predicate.Item) predicate.CustomItem {
	return predicate.CustomItem(func(s *sql.Selector) {
		step := newVariantsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.CustomItem) predicate.CustomItem {
	return predicate.CustomItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.CustomItem) predicate.CustomItem {
	return predicate.CustomItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.CustomItem) predicate.CustomItem {
	return predicate.CustomItem(sql.NotPredicates(p))
}
