mutation {
	createItems(items:  [{
		id: 0,
		available: true,
		identifier: "Item 1",
		name: "Item 1",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: true
		price: 0.1
	},
		{
		id: 1,
		available: true,
		identifier: "Item 2",
		name: "Item 2",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: true
		price: 0.2
	},
		{
		id: 3,
		available: true,
		identifier: "Item 3",
		name: "Item 3",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: true
		price: 0.3
	},
		{
		id: 4,
		available: true,
		identifier: "Item 4",
		name: "Item 4",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: true
		price: 0.4
	},
		{
		id: 5,
		available: true,
		identifier: "Variant 1",
		name: "Variant 1",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: false
		price: 0.2
	},
		{
		id: 6,
		available: true,
		identifier: "Variant 2",
		name: "Variant 2",
		image:"https://fakeimg.pl/1080x1920",
		isOneOff: false
		price: 0.3
	}
	])
	createCustomItems(items:  [
		{
			id: 3,
			exclusive: true,
			name: "Custom Test 1",
			variants: [5]
		},
		{
			id: 4,
			exclusive: true,
			dependsOn: 3,
			name: "Custom Test 1",
			variants: [6]
		}

	])
}
