// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CustomItemsColumns holds the columns for the "custom_items" table.
	CustomItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "exclusive", Type: field.TypeBool},
		{Name: "prev", Type: field.TypeInt, Nullable: true},
	}
	// CustomItemsTable holds the schema information for the "custom_items" table.
	CustomItemsTable = &schema.Table{
		Name:       "custom_items",
		Columns:    CustomItemsColumns,
		PrimaryKey: []*schema.Column{CustomItemsColumns[0]},
	}
	// ItemsColumns holds the columns for the "items" table.
	ItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "image", Type: field.TypeString},
		{Name: "in_stock", Type: field.TypeBool},
		{Name: "notes", Type: field.TypeString},
		{Name: "custom_item_variants", Type: field.TypeInt, Nullable: true},
		{Name: "selected_custom_item_selected_variants", Type: field.TypeInt, Nullable: true},
	}
	// ItemsTable holds the schema information for the "items" table.
	ItemsTable = &schema.Table{
		Name:       "items",
		Columns:    ItemsColumns,
		PrimaryKey: []*schema.Column{ItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "items_custom_items_variants",
				Columns:    []*schema.Column{ItemsColumns[6]},
				RefColumns: []*schema.Column{CustomItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "items_selected_custom_items_selected_variants",
				Columns:    []*schema.Column{ItemsColumns[7]},
				RefColumns: []*schema.Column{SelectedCustomItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrdersColumns holds the columns for the "orders" table.
	OrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "submitted", Type: field.TypeTime},
		{Name: "identifier", Type: field.TypeString},
		{Name: "state", Type: field.TypeEnum, Enums: []string{"created", "pending", "compleated", "cancelled"}, Default: "created"},
		{Name: "total", Type: field.TypeFloat64},
	}
	// OrdersTable holds the schema information for the "orders" table.
	OrdersTable = &schema.Table{
		Name:       "orders",
		Columns:    OrdersColumns,
		PrimaryKey: []*schema.Column{OrdersColumns[0]},
	}
	// OrderCustomItemsColumns holds the columns for the "order_custom_items" table.
	OrderCustomItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "order_custom_items", Type: field.TypeInt, Nullable: true},
		{Name: "order_custom_item_master_custom_item", Type: field.TypeInt, Nullable: true},
	}
	// OrderCustomItemsTable holds the schema information for the "order_custom_items" table.
	OrderCustomItemsTable = &schema.Table{
		Name:       "order_custom_items",
		Columns:    OrderCustomItemsColumns,
		PrimaryKey: []*schema.Column{OrderCustomItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_custom_items_orders_custom_items",
				Columns:    []*schema.Column{OrderCustomItemsColumns[2]},
				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "order_custom_items_custom_items_master_custom_item",
				Columns:    []*schema.Column{OrderCustomItemsColumns[3]},
				RefColumns: []*schema.Column{CustomItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// OrderItemsColumns holds the columns for the "order_items" table.
	OrderItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "quantity", Type: field.TypeInt},
		{Name: "order_items", Type: field.TypeInt, Nullable: true},
		{Name: "order_item_item", Type: field.TypeInt, Nullable: true},
	}
	// OrderItemsTable holds the schema information for the "order_items" table.
	OrderItemsTable = &schema.Table{
		Name:       "order_items",
		Columns:    OrderItemsColumns,
		PrimaryKey: []*schema.Column{OrderItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "order_items_orders_items",
				Columns:    []*schema.Column{OrderItemsColumns[2]},
				RefColumns: []*schema.Column{OrdersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "order_items_items_item",
				Columns:    []*schema.Column{OrderItemsColumns[3]},
				RefColumns: []*schema.Column{ItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SelectedCustomItemsColumns holds the columns for the "selected_custom_items" table.
	SelectedCustomItemsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "order_custom_item_selected_custom_items", Type: field.TypeInt, Nullable: true},
		{Name: "selected_custom_item_custom_item", Type: field.TypeInt, Nullable: true},
	}
	// SelectedCustomItemsTable holds the schema information for the "selected_custom_items" table.
	SelectedCustomItemsTable = &schema.Table{
		Name:       "selected_custom_items",
		Columns:    SelectedCustomItemsColumns,
		PrimaryKey: []*schema.Column{SelectedCustomItemsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "selected_custom_items_order_custom_items_selected_custom_items",
				Columns:    []*schema.Column{SelectedCustomItemsColumns[1]},
				RefColumns: []*schema.Column{OrderCustomItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "selected_custom_items_custom_items_custom_item",
				Columns:    []*schema.Column{SelectedCustomItemsColumns[2]},
				RefColumns: []*schema.Column{CustomItemsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CustomItemsTable,
		ItemsTable,
		OrdersTable,
		OrderCustomItemsTable,
		OrderItemsTable,
		SelectedCustomItemsTable,
	}
)

func init() {
	ItemsTable.ForeignKeys[0].RefTable = CustomItemsTable
	ItemsTable.ForeignKeys[1].RefTable = SelectedCustomItemsTable
	OrderCustomItemsTable.ForeignKeys[0].RefTable = OrdersTable
	OrderCustomItemsTable.ForeignKeys[1].RefTable = CustomItemsTable
	OrderItemsTable.ForeignKeys[0].RefTable = OrdersTable
	OrderItemsTable.ForeignKeys[1].RefTable = ItemsTable
	SelectedCustomItemsTable.ForeignKeys[0].RefTable = OrderCustomItemsTable
	SelectedCustomItemsTable.ForeignKeys[1].RefTable = CustomItemsTable
}
