/* eslint-disable */
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: number; output: number; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * Define a Relay Cursor type:
   * https://relay.dev/graphql/connections.htm#sec-Cursor
   */
  Cursor: { input: any; output: any; }
  Time: { input: string; output: string; }
};

/**
 * CreateCustomItemInput is used for create CustomItem object.
 * Input was generated by ent.
 */
export type CreateCustomItemInput = {
  /** if false then one or more variants can be selected at once */
  allowOnlyOne: Scalars['Boolean']['input'];
  name: Scalars['String']['input'];
  /** The id of the previous to selectable custom item */
  prev?: InputMaybe<Scalars['Int']['input']>;
  variantIDs: Array<Scalars['ID']['input']>;
};

/**
 * CreateItemInput is used for create Item object.
 * Input was generated by ent.
 */
export type CreateItemInput = {
  /** an url; eg.: https://example.com/cheesecake.png */
  image: Scalars['String']['input'];
  /** weather the item is (physically) in stock */
  inStock: Scalars['Boolean']['input'];
  /** eg.: cheesecake */
  name: Scalars['String']['input'];
  /** Custom text, which will be displayed */
  notes: Scalars['String']['input'];
  price: Scalars['Float']['input'];
};

/**
 * CreateOrderCustomItemInput is used for create OrderCustomItem object.
 * Input was generated by ent.
 */
export type CreateOrderCustomItemInput = {
  masterCustomItemID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
  selectedCustomItemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  selectedCustomItems: Array<CreateSelectedCustomItemInput>;
};

/**
 * CreateOrderInput is used for create Order object.
 * Input was generated by ent.
 */
export type CreateOrderInput = {
  customItemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  customItems: Array<CreateOrderCustomItemInput>;
  itemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  items: Array<CreateOrderItemInput>;
  state?: InputMaybe<OrderState>;
};

/**
 * CreateOrderItemInput is used for create OrderItem object.
 * Input was generated by ent.
 */
export type CreateOrderItemInput = {
  itemID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
};

/**
 * CreateSelectedCustomItemInput is used for create SelectedCustomItem object.
 * Input was generated by ent.
 */
export type CreateSelectedCustomItemInput = {
  customItemID: Scalars['ID']['input'];
  selectedVariantIDs: Array<Scalars['ID']['input']>;
};

export type CustomItem = Node & {
  __typename?: 'CustomItem';
  /** if false then one or more variants can be selected at once */
  allowOnlyOne: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  /** The id of the previous to selectable custom item */
  prev?: Maybe<Scalars['Int']['output']>;
  variants: Array<Item>;
};

/**
 * CustomItemWhereInput is used for filtering CustomItem objects.
 * Input was generated by ent.
 */
export type CustomItemWhereInput = {
  /** allow_only_one field predicates */
  allowOnlyOne?: InputMaybe<Scalars['Boolean']['input']>;
  allowOnlyOneNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  and?: InputMaybe<Array<CustomItemWhereInput>>;
  /** variants edge predicates */
  hasVariants?: InputMaybe<Scalars['Boolean']['input']>;
  hasVariantsWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<CustomItemWhereInput>;
  or?: InputMaybe<Array<CustomItemWhereInput>>;
  /** prev field predicates */
  prev?: InputMaybe<Scalars['Int']['input']>;
  prevGT?: InputMaybe<Scalars['Int']['input']>;
  prevGTE?: InputMaybe<Scalars['Int']['input']>;
  prevIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  prevIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  prevLT?: InputMaybe<Scalars['Int']['input']>;
  prevLTE?: InputMaybe<Scalars['Int']['input']>;
  prevNEQ?: InputMaybe<Scalars['Int']['input']>;
  prevNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  prevNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Item = Node & {
  __typename?: 'Item';
  id: Scalars['ID']['output'];
  /** an url; eg.: https://example.com/cheesecake.png */
  image: Scalars['String']['output'];
  /** weather the item is (physically) in stock */
  inStock: Scalars['Boolean']['output'];
  /** eg.: cheesecake */
  name: Scalars['String']['output'];
  /** Custom text, which will be displayed */
  notes: Scalars['String']['output'];
  price: Scalars['Float']['output'];
};

/**
 * ItemWhereInput is used for filtering Item objects.
 * Input was generated by ent.
 */
export type ItemWhereInput = {
  and?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** image field predicates */
  image?: InputMaybe<Scalars['String']['input']>;
  imageContains?: InputMaybe<Scalars['String']['input']>;
  imageContainsFold?: InputMaybe<Scalars['String']['input']>;
  imageEqualFold?: InputMaybe<Scalars['String']['input']>;
  imageGT?: InputMaybe<Scalars['String']['input']>;
  imageGTE?: InputMaybe<Scalars['String']['input']>;
  imageHasPrefix?: InputMaybe<Scalars['String']['input']>;
  imageHasSuffix?: InputMaybe<Scalars['String']['input']>;
  imageIn?: InputMaybe<Array<Scalars['String']['input']>>;
  imageLT?: InputMaybe<Scalars['String']['input']>;
  imageLTE?: InputMaybe<Scalars['String']['input']>;
  imageNEQ?: InputMaybe<Scalars['String']['input']>;
  imageNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** in_stock field predicates */
  inStock?: InputMaybe<Scalars['Boolean']['input']>;
  inStockNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<ItemWhereInput>;
  /** notes field predicates */
  notes?: InputMaybe<Scalars['String']['input']>;
  notesContains?: InputMaybe<Scalars['String']['input']>;
  notesContainsFold?: InputMaybe<Scalars['String']['input']>;
  notesEqualFold?: InputMaybe<Scalars['String']['input']>;
  notesGT?: InputMaybe<Scalars['String']['input']>;
  notesGTE?: InputMaybe<Scalars['String']['input']>;
  notesHasPrefix?: InputMaybe<Scalars['String']['input']>;
  notesHasSuffix?: InputMaybe<Scalars['String']['input']>;
  notesIn?: InputMaybe<Array<Scalars['String']['input']>>;
  notesLT?: InputMaybe<Scalars['String']['input']>;
  notesLTE?: InputMaybe<Scalars['String']['input']>;
  notesNEQ?: InputMaybe<Scalars['String']['input']>;
  notesNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  or?: InputMaybe<Array<ItemWhereInput>>;
  /** price field predicates */
  price?: InputMaybe<Scalars['Float']['input']>;
  priceGT?: InputMaybe<Scalars['Float']['input']>;
  priceGTE?: InputMaybe<Scalars['Float']['input']>;
  priceIn?: InputMaybe<Array<Scalars['Float']['input']>>;
  priceLT?: InputMaybe<Scalars['Float']['input']>;
  priceLTE?: InputMaybe<Scalars['Float']['input']>;
  priceNEQ?: InputMaybe<Scalars['Float']['input']>;
  priceNotIn?: InputMaybe<Array<Scalars['Float']['input']>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createCustomItem: CustomItem;
  createItem: Item;
  createOrder: Order;
  deleteCustomItem: Scalars['ID']['output'];
  deleteCustomItems: Array<Scalars['ID']['output']>;
  deleteItem: Scalars['ID']['output'];
  deleteItems: Array<Scalars['ID']['output']>;
  updateCustomItem: CustomItem;
  updateItem: Item;
  updateOrder: Order;
};


export type MutationCreateCustomItemArgs = {
  input: CreateCustomItemInput;
};


export type MutationCreateItemArgs = {
  input: CreateItemInput;
};


export type MutationCreateOrderArgs = {
  input: CreateOrderInput;
};


export type MutationDeleteCustomItemArgs = {
  id: Scalars['ID']['input'];
};


export type MutationDeleteCustomItemsArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type MutationDeleteItemArgs = {
  id: Scalars['ID']['input'];
};


export type MutationDeleteItemsArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type MutationUpdateCustomItemArgs = {
  id: Scalars['ID']['input'];
  input: UpdateCustomItemInput;
};


export type MutationUpdateItemArgs = {
  id: Scalars['ID']['input'];
  input: UpdateItemInput;
};


export type MutationUpdateOrderArgs = {
  id: Scalars['ID']['input'];
  input: UpdateOrderInput;
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID']['output'];
};

export enum NotificationType {
  CustomItemsChanged = 'CUSTOM_ITEMS_CHANGED',
  ItemsChanged = 'ITEMS_CHANGED',
  NewOrder = 'NEW_ORDER',
  OrderUpdated = 'ORDER_UPDATED'
}

export type Order = Node & {
  __typename?: 'Order';
  customItems?: Maybe<Array<OrderCustomItem>>;
  id: Scalars['ID']['output'];
  /** A sequencially generated string to identifiy an open order */
  identifier: Scalars['String']['output'];
  items?: Maybe<Array<OrderItem>>;
  state: OrderState;
  /** The time when the order has been submitted */
  submitted: Scalars['Time']['output'];
  /** on server generated orders total */
  total: Scalars['Float']['output'];
};

/** A connection to a list of items. */
export type OrderConnection = {
  __typename?: 'OrderConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<OrderEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

export type OrderCustomItem = Node & {
  __typename?: 'OrderCustomItem';
  id: Scalars['ID']['output'];
  masterCustomItem: CustomItem;
  quantity: Scalars['Int']['output'];
  selectedCustomItems?: Maybe<Array<SelectedCustomItem>>;
};

/**
 * OrderCustomItemWhereInput is used for filtering OrderCustomItem objects.
 * Input was generated by ent.
 */
export type OrderCustomItemWhereInput = {
  and?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** master_custom_item edge predicates */
  hasMasterCustomItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasMasterCustomItemWith?: InputMaybe<Array<CustomItemWhereInput>>;
  /** selected_custom_items edge predicates */
  hasSelectedCustomItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasSelectedCustomItemsWith?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<OrderCustomItemWhereInput>;
  or?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** quantity field predicates */
  quantity?: InputMaybe<Scalars['Int']['input']>;
  quantityGT?: InputMaybe<Scalars['Int']['input']>;
  quantityGTE?: InputMaybe<Scalars['Int']['input']>;
  quantityIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT?: InputMaybe<Scalars['Int']['input']>;
  quantityLTE?: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ?: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/** An edge in a connection. */
export type OrderEdge = {
  __typename?: 'OrderEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Order>;
};

export type OrderItem = Node & {
  __typename?: 'OrderItem';
  id: Scalars['ID']['output'];
  item: Item;
  quantity: Scalars['Int']['output'];
};

/**
 * OrderItemWhereInput is used for filtering OrderItem objects.
 * Input was generated by ent.
 */
export type OrderItemWhereInput = {
  and?: InputMaybe<Array<OrderItemWhereInput>>;
  /** item edge predicates */
  hasItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasItemWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<OrderItemWhereInput>;
  or?: InputMaybe<Array<OrderItemWhereInput>>;
  /** quantity field predicates */
  quantity?: InputMaybe<Scalars['Int']['input']>;
  quantityGT?: InputMaybe<Scalars['Int']['input']>;
  quantityGTE?: InputMaybe<Scalars['Int']['input']>;
  quantityIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT?: InputMaybe<Scalars['Int']['input']>;
  quantityLTE?: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ?: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/** Ordering options for Order connections */
export type OrderOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Orders. */
  field: OrderOrderField;
};

/** Properties by which Order connections can be ordered. */
export enum OrderOrderField {
  State = 'STATE',
  Submitted = 'SUBMITTED',
  Total = 'TOTAL'
}

/** OrderState is enum for the field state */
export enum OrderState {
  Cancelled = 'cancelled',
  Compleated = 'compleated',
  Created = 'created',
  Pending = 'pending'
}

/**
 * OrderWhereInput is used for filtering Order objects.
 * Input was generated by ent.
 */
export type OrderWhereInput = {
  and?: InputMaybe<Array<OrderWhereInput>>;
  /** custom_items edge predicates */
  hasCustomItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasCustomItemsWith?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** items edge predicates */
  hasItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasItemsWith?: InputMaybe<Array<OrderItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** identifier field predicates */
  identifier?: InputMaybe<Scalars['String']['input']>;
  identifierContains?: InputMaybe<Scalars['String']['input']>;
  identifierContainsFold?: InputMaybe<Scalars['String']['input']>;
  identifierEqualFold?: InputMaybe<Scalars['String']['input']>;
  identifierGT?: InputMaybe<Scalars['String']['input']>;
  identifierGTE?: InputMaybe<Scalars['String']['input']>;
  identifierHasPrefix?: InputMaybe<Scalars['String']['input']>;
  identifierHasSuffix?: InputMaybe<Scalars['String']['input']>;
  identifierIn?: InputMaybe<Array<Scalars['String']['input']>>;
  identifierLT?: InputMaybe<Scalars['String']['input']>;
  identifierLTE?: InputMaybe<Scalars['String']['input']>;
  identifierNEQ?: InputMaybe<Scalars['String']['input']>;
  identifierNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<OrderWhereInput>;
  or?: InputMaybe<Array<OrderWhereInput>>;
  /** state field predicates */
  state?: InputMaybe<OrderState>;
  stateIn?: InputMaybe<Array<OrderState>>;
  stateNEQ?: InputMaybe<OrderState>;
  stateNotIn?: InputMaybe<Array<OrderState>>;
  /** submitted field predicates */
  submitted?: InputMaybe<Scalars['Time']['input']>;
  submittedGT?: InputMaybe<Scalars['Time']['input']>;
  submittedGTE?: InputMaybe<Scalars['Time']['input']>;
  submittedIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  submittedLT?: InputMaybe<Scalars['Time']['input']>;
  submittedLTE?: InputMaybe<Scalars['Time']['input']>;
  submittedNEQ?: InputMaybe<Scalars['Time']['input']>;
  submittedNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** total field predicates */
  total?: InputMaybe<Scalars['Float']['input']>;
  totalGT?: InputMaybe<Scalars['Float']['input']>;
  totalGTE?: InputMaybe<Scalars['Float']['input']>;
  totalIn?: InputMaybe<Array<Scalars['Float']['input']>>;
  totalLT?: InputMaybe<Scalars['Float']['input']>;
  totalLTE?: InputMaybe<Scalars['Float']['input']>;
  totalNEQ?: InputMaybe<Scalars['Float']['input']>;
  totalNotIn?: InputMaybe<Array<Scalars['Float']['input']>>;
};

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['Cursor']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['Cursor']['output']>;
};

export type Query = {
  __typename?: 'Query';
  customItems: Array<CustomItem>;
  items: Array<Item>;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  orders: OrderConnection;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type QueryOrdersArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<OrderOrder>;
  where?: InputMaybe<OrderWhereInput>;
};

export type SelectedCustomItem = Node & {
  __typename?: 'SelectedCustomItem';
  customItem: CustomItem;
  id: Scalars['ID']['output'];
  selectedVariants: Array<Item>;
};

/**
 * SelectedCustomItemWhereInput is used for filtering SelectedCustomItem objects.
 * Input was generated by ent.
 */
export type SelectedCustomItemWhereInput = {
  and?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
  /** custom_item edge predicates */
  hasCustomItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasCustomItemWith?: InputMaybe<Array<CustomItemWhereInput>>;
  /** selected_variants edge predicates */
  hasSelectedVariants?: InputMaybe<Scalars['Boolean']['input']>;
  hasSelectedVariantsWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<SelectedCustomItemWhereInput>;
  or?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
};

export type Subscription = {
  __typename?: 'Subscription';
  notfiy: NotificationType;
};


export type SubscriptionNotfiyArgs = {
  type?: InputMaybe<Array<NotificationType>>;
};

/**
 * UpdateCustomItemInput is used for update CustomItem object.
 * Input was generated by ent.
 */
export type UpdateCustomItemInput = {
  addVariantIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** if false then one or more variants can be selected at once */
  allowOnlyOne?: InputMaybe<Scalars['Boolean']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  removeVariantIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
};

/**
 * UpdateItemInput is used for update Item object.
 * Input was generated by ent.
 */
export type UpdateItemInput = {
  /** an url; eg.: https://example.com/cheesecake.png */
  image?: InputMaybe<Scalars['String']['input']>;
  /** weather the item is (physically) in stock */
  inStock?: InputMaybe<Scalars['Boolean']['input']>;
  /** eg.: cheesecake */
  name?: InputMaybe<Scalars['String']['input']>;
  /** Custom text, which will be displayed */
  notes?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
};

/**
 * UpdateOrderInput is used for update Order object.
 * Input was generated by ent.
 */
export type UpdateOrderInput = {
  state?: InputMaybe<OrderState>;
};

export type QueryItemAndCustomItemQueryVariables = Exact<{ [key: string]: never; }>;


export type QueryItemAndCustomItemQuery = { __typename?: 'Query', items: Array<{ __typename?: 'Item', id: number, name: string, price: number, image: string, inStock: boolean, notes: string }>, customItems: Array<{ __typename?: 'CustomItem', id: number, name: string, allowOnlyOne: boolean, prev?: number | null, variants: Array<{ __typename?: 'Item', id: number }> }> };

export type CreateOrderMutationVariables = Exact<{
  order: CreateOrderInput;
}>;


export type CreateOrderMutation = { __typename?: 'Mutation', createOrder: { __typename?: 'Order', id: number, identifier: string } };


export const QueryItemAndCustomItemDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"QueryItemAndCustomItem"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"items"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"price"}},{"kind":"Field","name":{"kind":"Name","value":"image"}},{"kind":"Field","name":{"kind":"Name","value":"inStock"}},{"kind":"Field","name":{"kind":"Name","value":"notes"}}]}},{"kind":"Field","name":{"kind":"Name","value":"customItems"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"allowOnlyOne"}},{"kind":"Field","name":{"kind":"Name","value":"prev"}},{"kind":"Field","name":{"kind":"Name","value":"variants"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}}]}}]}}]}}]} as unknown as DocumentNode<QueryItemAndCustomItemQuery, QueryItemAndCustomItemQueryVariables>;
export const CreateOrderDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"mutation","name":{"kind":"Name","value":"CreateOrder"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"order"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"CreateOrderInput"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"createOrder"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"input"},"value":{"kind":"Variable","name":{"kind":"Name","value":"order"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"identifier"}}]}}]}}]} as unknown as DocumentNode<CreateOrderMutation, CreateOrderMutationVariables>;
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: number; output: number; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /**
   * Define a Relay Cursor type:
   * https://relay.dev/graphql/connections.htm#sec-Cursor
   */
  Cursor: { input: any; output: any; }
  Time: { input: string; output: string; }
};

/**
 * CreateCustomItemInput is used for create CustomItem object.
 * Input was generated by ent.
 */
export type CreateCustomItemInput = {
  /** if false then one or more variants can be selected at once */
  allowOnlyOne: Scalars['Boolean']['input'];
  name: Scalars['String']['input'];
  /** The id of the previous to selectable custom item */
  prev?: InputMaybe<Scalars['Int']['input']>;
  variantIDs: Array<Scalars['ID']['input']>;
};

/**
 * CreateItemInput is used for create Item object.
 * Input was generated by ent.
 */
export type CreateItemInput = {
  /** an url; eg.: https://example.com/cheesecake.png */
  image: Scalars['String']['input'];
  /** weather the item is (physically) in stock */
  inStock: Scalars['Boolean']['input'];
  /** eg.: cheesecake */
  name: Scalars['String']['input'];
  /** Custom text, which will be displayed */
  notes: Scalars['String']['input'];
  price: Scalars['Float']['input'];
};

/**
 * CreateOrderCustomItemInput is used for create OrderCustomItem object.
 * Input was generated by ent.
 */
export type CreateOrderCustomItemInput = {
  masterCustomItemID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
  selectedCustomItemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  selectedCustomItems: Array<CreateSelectedCustomItemInput>;
};

/**
 * CreateOrderInput is used for create Order object.
 * Input was generated by ent.
 */
export type CreateOrderInput = {
  customItemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  customItems: Array<CreateOrderCustomItemInput>;
  itemIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  items: Array<CreateOrderItemInput>;
  state?: InputMaybe<OrderState>;
};

/**
 * CreateOrderItemInput is used for create OrderItem object.
 * Input was generated by ent.
 */
export type CreateOrderItemInput = {
  itemID: Scalars['ID']['input'];
  quantity: Scalars['Int']['input'];
};

/**
 * CreateSelectedCustomItemInput is used for create SelectedCustomItem object.
 * Input was generated by ent.
 */
export type CreateSelectedCustomItemInput = {
  customItemID: Scalars['ID']['input'];
  selectedVariantIDs: Array<Scalars['ID']['input']>;
};

export type CustomItem = Node & {
  __typename?: 'CustomItem';
  /** if false then one or more variants can be selected at once */
  allowOnlyOne: Scalars['Boolean']['output'];
  id: Scalars['ID']['output'];
  name: Scalars['String']['output'];
  /** The id of the previous to selectable custom item */
  prev?: Maybe<Scalars['Int']['output']>;
  variants: Array<Item>;
};

/**
 * CustomItemWhereInput is used for filtering CustomItem objects.
 * Input was generated by ent.
 */
export type CustomItemWhereInput = {
  /** allow_only_one field predicates */
  allowOnlyOne?: InputMaybe<Scalars['Boolean']['input']>;
  allowOnlyOneNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  and?: InputMaybe<Array<CustomItemWhereInput>>;
  /** variants edge predicates */
  hasVariants?: InputMaybe<Scalars['Boolean']['input']>;
  hasVariantsWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<CustomItemWhereInput>;
  or?: InputMaybe<Array<CustomItemWhereInput>>;
  /** prev field predicates */
  prev?: InputMaybe<Scalars['Int']['input']>;
  prevGT?: InputMaybe<Scalars['Int']['input']>;
  prevGTE?: InputMaybe<Scalars['Int']['input']>;
  prevIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  prevIsNil?: InputMaybe<Scalars['Boolean']['input']>;
  prevLT?: InputMaybe<Scalars['Int']['input']>;
  prevLTE?: InputMaybe<Scalars['Int']['input']>;
  prevNEQ?: InputMaybe<Scalars['Int']['input']>;
  prevNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  prevNotNil?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Item = Node & {
  __typename?: 'Item';
  id: Scalars['ID']['output'];
  /** an url; eg.: https://example.com/cheesecake.png */
  image: Scalars['String']['output'];
  /** weather the item is (physically) in stock */
  inStock: Scalars['Boolean']['output'];
  /** eg.: cheesecake */
  name: Scalars['String']['output'];
  /** Custom text, which will be displayed */
  notes: Scalars['String']['output'];
  price: Scalars['Float']['output'];
};

/**
 * ItemWhereInput is used for filtering Item objects.
 * Input was generated by ent.
 */
export type ItemWhereInput = {
  and?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** image field predicates */
  image?: InputMaybe<Scalars['String']['input']>;
  imageContains?: InputMaybe<Scalars['String']['input']>;
  imageContainsFold?: InputMaybe<Scalars['String']['input']>;
  imageEqualFold?: InputMaybe<Scalars['String']['input']>;
  imageGT?: InputMaybe<Scalars['String']['input']>;
  imageGTE?: InputMaybe<Scalars['String']['input']>;
  imageHasPrefix?: InputMaybe<Scalars['String']['input']>;
  imageHasSuffix?: InputMaybe<Scalars['String']['input']>;
  imageIn?: InputMaybe<Array<Scalars['String']['input']>>;
  imageLT?: InputMaybe<Scalars['String']['input']>;
  imageLTE?: InputMaybe<Scalars['String']['input']>;
  imageNEQ?: InputMaybe<Scalars['String']['input']>;
  imageNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  /** in_stock field predicates */
  inStock?: InputMaybe<Scalars['Boolean']['input']>;
  inStockNEQ?: InputMaybe<Scalars['Boolean']['input']>;
  /** name field predicates */
  name?: InputMaybe<Scalars['String']['input']>;
  nameContains?: InputMaybe<Scalars['String']['input']>;
  nameContainsFold?: InputMaybe<Scalars['String']['input']>;
  nameEqualFold?: InputMaybe<Scalars['String']['input']>;
  nameGT?: InputMaybe<Scalars['String']['input']>;
  nameGTE?: InputMaybe<Scalars['String']['input']>;
  nameHasPrefix?: InputMaybe<Scalars['String']['input']>;
  nameHasSuffix?: InputMaybe<Scalars['String']['input']>;
  nameIn?: InputMaybe<Array<Scalars['String']['input']>>;
  nameLT?: InputMaybe<Scalars['String']['input']>;
  nameLTE?: InputMaybe<Scalars['String']['input']>;
  nameNEQ?: InputMaybe<Scalars['String']['input']>;
  nameNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<ItemWhereInput>;
  /** notes field predicates */
  notes?: InputMaybe<Scalars['String']['input']>;
  notesContains?: InputMaybe<Scalars['String']['input']>;
  notesContainsFold?: InputMaybe<Scalars['String']['input']>;
  notesEqualFold?: InputMaybe<Scalars['String']['input']>;
  notesGT?: InputMaybe<Scalars['String']['input']>;
  notesGTE?: InputMaybe<Scalars['String']['input']>;
  notesHasPrefix?: InputMaybe<Scalars['String']['input']>;
  notesHasSuffix?: InputMaybe<Scalars['String']['input']>;
  notesIn?: InputMaybe<Array<Scalars['String']['input']>>;
  notesLT?: InputMaybe<Scalars['String']['input']>;
  notesLTE?: InputMaybe<Scalars['String']['input']>;
  notesNEQ?: InputMaybe<Scalars['String']['input']>;
  notesNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  or?: InputMaybe<Array<ItemWhereInput>>;
  /** price field predicates */
  price?: InputMaybe<Scalars['Float']['input']>;
  priceGT?: InputMaybe<Scalars['Float']['input']>;
  priceGTE?: InputMaybe<Scalars['Float']['input']>;
  priceIn?: InputMaybe<Array<Scalars['Float']['input']>>;
  priceLT?: InputMaybe<Scalars['Float']['input']>;
  priceLTE?: InputMaybe<Scalars['Float']['input']>;
  priceNEQ?: InputMaybe<Scalars['Float']['input']>;
  priceNotIn?: InputMaybe<Array<Scalars['Float']['input']>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  createCustomItem: CustomItem;
  createItem: Item;
  createOrder: Order;
  deleteCustomItem: Scalars['ID']['output'];
  deleteCustomItems: Array<Scalars['ID']['output']>;
  deleteItem: Scalars['ID']['output'];
  deleteItems: Array<Scalars['ID']['output']>;
  updateCustomItem: CustomItem;
  updateItem: Item;
  updateOrder: Order;
};


export type MutationCreateCustomItemArgs = {
  input: CreateCustomItemInput;
};


export type MutationCreateItemArgs = {
  input: CreateItemInput;
};


export type MutationCreateOrderArgs = {
  input: CreateOrderInput;
};


export type MutationDeleteCustomItemArgs = {
  id: Scalars['ID']['input'];
};


export type MutationDeleteCustomItemsArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type MutationDeleteItemArgs = {
  id: Scalars['ID']['input'];
};


export type MutationDeleteItemsArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type MutationUpdateCustomItemArgs = {
  id: Scalars['ID']['input'];
  input: UpdateCustomItemInput;
};


export type MutationUpdateItemArgs = {
  id: Scalars['ID']['input'];
  input: UpdateItemInput;
};


export type MutationUpdateOrderArgs = {
  id: Scalars['ID']['input'];
  input: UpdateOrderInput;
};

/**
 * An object with an ID.
 * Follows the [Relay Global Object Identification Specification](https://relay.dev/graphql/objectidentification.htm)
 */
export type Node = {
  /** The id of the object. */
  id: Scalars['ID']['output'];
};

export enum NotificationType {
  CustomItemsChanged = 'CUSTOM_ITEMS_CHANGED',
  ItemsChanged = 'ITEMS_CHANGED',
  NewOrder = 'NEW_ORDER',
  OrderUpdated = 'ORDER_UPDATED'
}

export type Order = Node & {
  __typename?: 'Order';
  customItems?: Maybe<Array<OrderCustomItem>>;
  id: Scalars['ID']['output'];
  /** A sequencially generated string to identifiy an open order */
  identifier: Scalars['String']['output'];
  items?: Maybe<Array<OrderItem>>;
  state: OrderState;
  /** The time when the order has been submitted */
  submitted: Scalars['Time']['output'];
  /** on server generated orders total */
  total: Scalars['Float']['output'];
};

/** A connection to a list of items. */
export type OrderConnection = {
  __typename?: 'OrderConnection';
  /** A list of edges. */
  edges?: Maybe<Array<Maybe<OrderEdge>>>;
  /** Information to aid in pagination. */
  pageInfo: PageInfo;
  /** Identifies the total count of items in the connection. */
  totalCount: Scalars['Int']['output'];
};

export type OrderCustomItem = Node & {
  __typename?: 'OrderCustomItem';
  id: Scalars['ID']['output'];
  masterCustomItem: CustomItem;
  quantity: Scalars['Int']['output'];
  selectedCustomItems?: Maybe<Array<SelectedCustomItem>>;
};

/**
 * OrderCustomItemWhereInput is used for filtering OrderCustomItem objects.
 * Input was generated by ent.
 */
export type OrderCustomItemWhereInput = {
  and?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** master_custom_item edge predicates */
  hasMasterCustomItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasMasterCustomItemWith?: InputMaybe<Array<CustomItemWhereInput>>;
  /** selected_custom_items edge predicates */
  hasSelectedCustomItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasSelectedCustomItemsWith?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<OrderCustomItemWhereInput>;
  or?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** quantity field predicates */
  quantity?: InputMaybe<Scalars['Int']['input']>;
  quantityGT?: InputMaybe<Scalars['Int']['input']>;
  quantityGTE?: InputMaybe<Scalars['Int']['input']>;
  quantityIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT?: InputMaybe<Scalars['Int']['input']>;
  quantityLTE?: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ?: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/** Possible directions in which to order a list of items when provided an `orderBy` argument. */
export enum OrderDirection {
  /** Specifies an ascending order for a given `orderBy` argument. */
  Asc = 'ASC',
  /** Specifies a descending order for a given `orderBy` argument. */
  Desc = 'DESC'
}

/** An edge in a connection. */
export type OrderEdge = {
  __typename?: 'OrderEdge';
  /** A cursor for use in pagination. */
  cursor: Scalars['Cursor']['output'];
  /** The item at the end of the edge. */
  node?: Maybe<Order>;
};

export type OrderItem = Node & {
  __typename?: 'OrderItem';
  id: Scalars['ID']['output'];
  item: Item;
  quantity: Scalars['Int']['output'];
};

/**
 * OrderItemWhereInput is used for filtering OrderItem objects.
 * Input was generated by ent.
 */
export type OrderItemWhereInput = {
  and?: InputMaybe<Array<OrderItemWhereInput>>;
  /** item edge predicates */
  hasItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasItemWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<OrderItemWhereInput>;
  or?: InputMaybe<Array<OrderItemWhereInput>>;
  /** quantity field predicates */
  quantity?: InputMaybe<Scalars['Int']['input']>;
  quantityGT?: InputMaybe<Scalars['Int']['input']>;
  quantityGTE?: InputMaybe<Scalars['Int']['input']>;
  quantityIn?: InputMaybe<Array<Scalars['Int']['input']>>;
  quantityLT?: InputMaybe<Scalars['Int']['input']>;
  quantityLTE?: InputMaybe<Scalars['Int']['input']>;
  quantityNEQ?: InputMaybe<Scalars['Int']['input']>;
  quantityNotIn?: InputMaybe<Array<Scalars['Int']['input']>>;
};

/** Ordering options for Order connections */
export type OrderOrder = {
  /** The ordering direction. */
  direction?: OrderDirection;
  /** The field by which to order Orders. */
  field: OrderOrderField;
};

/** Properties by which Order connections can be ordered. */
export enum OrderOrderField {
  State = 'STATE',
  Submitted = 'SUBMITTED',
  Total = 'TOTAL'
}

/** OrderState is enum for the field state */
export enum OrderState {
  Cancelled = 'cancelled',
  Compleated = 'compleated',
  Created = 'created',
  Pending = 'pending'
}

/**
 * OrderWhereInput is used for filtering Order objects.
 * Input was generated by ent.
 */
export type OrderWhereInput = {
  and?: InputMaybe<Array<OrderWhereInput>>;
  /** custom_items edge predicates */
  hasCustomItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasCustomItemsWith?: InputMaybe<Array<OrderCustomItemWhereInput>>;
  /** items edge predicates */
  hasItems?: InputMaybe<Scalars['Boolean']['input']>;
  hasItemsWith?: InputMaybe<Array<OrderItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** identifier field predicates */
  identifier?: InputMaybe<Scalars['String']['input']>;
  identifierContains?: InputMaybe<Scalars['String']['input']>;
  identifierContainsFold?: InputMaybe<Scalars['String']['input']>;
  identifierEqualFold?: InputMaybe<Scalars['String']['input']>;
  identifierGT?: InputMaybe<Scalars['String']['input']>;
  identifierGTE?: InputMaybe<Scalars['String']['input']>;
  identifierHasPrefix?: InputMaybe<Scalars['String']['input']>;
  identifierHasSuffix?: InputMaybe<Scalars['String']['input']>;
  identifierIn?: InputMaybe<Array<Scalars['String']['input']>>;
  identifierLT?: InputMaybe<Scalars['String']['input']>;
  identifierLTE?: InputMaybe<Scalars['String']['input']>;
  identifierNEQ?: InputMaybe<Scalars['String']['input']>;
  identifierNotIn?: InputMaybe<Array<Scalars['String']['input']>>;
  not?: InputMaybe<OrderWhereInput>;
  or?: InputMaybe<Array<OrderWhereInput>>;
  /** state field predicates */
  state?: InputMaybe<OrderState>;
  stateIn?: InputMaybe<Array<OrderState>>;
  stateNEQ?: InputMaybe<OrderState>;
  stateNotIn?: InputMaybe<Array<OrderState>>;
  /** submitted field predicates */
  submitted?: InputMaybe<Scalars['Time']['input']>;
  submittedGT?: InputMaybe<Scalars['Time']['input']>;
  submittedGTE?: InputMaybe<Scalars['Time']['input']>;
  submittedIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  submittedLT?: InputMaybe<Scalars['Time']['input']>;
  submittedLTE?: InputMaybe<Scalars['Time']['input']>;
  submittedNEQ?: InputMaybe<Scalars['Time']['input']>;
  submittedNotIn?: InputMaybe<Array<Scalars['Time']['input']>>;
  /** total field predicates */
  total?: InputMaybe<Scalars['Float']['input']>;
  totalGT?: InputMaybe<Scalars['Float']['input']>;
  totalGTE?: InputMaybe<Scalars['Float']['input']>;
  totalIn?: InputMaybe<Array<Scalars['Float']['input']>>;
  totalLT?: InputMaybe<Scalars['Float']['input']>;
  totalLTE?: InputMaybe<Scalars['Float']['input']>;
  totalNEQ?: InputMaybe<Scalars['Float']['input']>;
  totalNotIn?: InputMaybe<Array<Scalars['Float']['input']>>;
};

/**
 * Information about pagination in a connection.
 * https://relay.dev/graphql/connections.htm#sec-undefined.PageInfo
 */
export type PageInfo = {
  __typename?: 'PageInfo';
  /** When paginating forwards, the cursor to continue. */
  endCursor?: Maybe<Scalars['Cursor']['output']>;
  /** When paginating forwards, are there more items? */
  hasNextPage: Scalars['Boolean']['output'];
  /** When paginating backwards, are there more items? */
  hasPreviousPage: Scalars['Boolean']['output'];
  /** When paginating backwards, the cursor to continue. */
  startCursor?: Maybe<Scalars['Cursor']['output']>;
};

export type Query = {
  __typename?: 'Query';
  customItems: Array<CustomItem>;
  items: Array<Item>;
  /** Fetches an object given its ID. */
  node?: Maybe<Node>;
  /** Lookup nodes by a list of IDs. */
  nodes: Array<Maybe<Node>>;
  orders: OrderConnection;
};


export type QueryNodeArgs = {
  id: Scalars['ID']['input'];
};


export type QueryNodesArgs = {
  ids: Array<Scalars['ID']['input']>;
};


export type QueryOrdersArgs = {
  after?: InputMaybe<Scalars['Cursor']['input']>;
  before?: InputMaybe<Scalars['Cursor']['input']>;
  first?: InputMaybe<Scalars['Int']['input']>;
  last?: InputMaybe<Scalars['Int']['input']>;
  orderBy?: InputMaybe<OrderOrder>;
  where?: InputMaybe<OrderWhereInput>;
};

export type SelectedCustomItem = Node & {
  __typename?: 'SelectedCustomItem';
  customItem: CustomItem;
  id: Scalars['ID']['output'];
  selectedVariants: Array<Item>;
};

/**
 * SelectedCustomItemWhereInput is used for filtering SelectedCustomItem objects.
 * Input was generated by ent.
 */
export type SelectedCustomItemWhereInput = {
  and?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
  /** custom_item edge predicates */
  hasCustomItem?: InputMaybe<Scalars['Boolean']['input']>;
  hasCustomItemWith?: InputMaybe<Array<CustomItemWhereInput>>;
  /** selected_variants edge predicates */
  hasSelectedVariants?: InputMaybe<Scalars['Boolean']['input']>;
  hasSelectedVariantsWith?: InputMaybe<Array<ItemWhereInput>>;
  /** id field predicates */
  id?: InputMaybe<Scalars['ID']['input']>;
  idGT?: InputMaybe<Scalars['ID']['input']>;
  idGTE?: InputMaybe<Scalars['ID']['input']>;
  idIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  idLT?: InputMaybe<Scalars['ID']['input']>;
  idLTE?: InputMaybe<Scalars['ID']['input']>;
  idNEQ?: InputMaybe<Scalars['ID']['input']>;
  idNotIn?: InputMaybe<Array<Scalars['ID']['input']>>;
  not?: InputMaybe<SelectedCustomItemWhereInput>;
  or?: InputMaybe<Array<SelectedCustomItemWhereInput>>;
};

export type Subscription = {
  __typename?: 'Subscription';
  notfiy: NotificationType;
};


export type SubscriptionNotfiyArgs = {
  type?: InputMaybe<Array<NotificationType>>;
};

/**
 * UpdateCustomItemInput is used for update CustomItem object.
 * Input was generated by ent.
 */
export type UpdateCustomItemInput = {
  addVariantIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
  /** if false then one or more variants can be selected at once */
  allowOnlyOne?: InputMaybe<Scalars['Boolean']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  removeVariantIDs?: InputMaybe<Array<Scalars['ID']['input']>>;
};

/**
 * UpdateItemInput is used for update Item object.
 * Input was generated by ent.
 */
export type UpdateItemInput = {
  /** an url; eg.: https://example.com/cheesecake.png */
  image?: InputMaybe<Scalars['String']['input']>;
  /** weather the item is (physically) in stock */
  inStock?: InputMaybe<Scalars['Boolean']['input']>;
  /** eg.: cheesecake */
  name?: InputMaybe<Scalars['String']['input']>;
  /** Custom text, which will be displayed */
  notes?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['Float']['input']>;
};

/**
 * UpdateOrderInput is used for update Order object.
 * Input was generated by ent.
 */
export type UpdateOrderInput = {
  state?: InputMaybe<OrderState>;
};
