// Code generated by ent, DO NOT EDIT.

package ordercustomitem

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/codecrafter404/bubble/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldLTE(FieldID, id))
}

// Quantity applies equality check predicate on the "quantity" field. It's identical to QuantityEQ.
func Quantity(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityEQ applies the EQ predicate on the "quantity" field.
func QuantityEQ(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldEQ(FieldQuantity, v))
}

// QuantityNEQ applies the NEQ predicate on the "quantity" field.
func QuantityNEQ(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldNEQ(FieldQuantity, v))
}

// QuantityIn applies the In predicate on the "quantity" field.
func QuantityIn(vs ...int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldIn(FieldQuantity, vs...))
}

// QuantityNotIn applies the NotIn predicate on the "quantity" field.
func QuantityNotIn(vs ...int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldNotIn(FieldQuantity, vs...))
}

// QuantityGT applies the GT predicate on the "quantity" field.
func QuantityGT(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldGT(FieldQuantity, v))
}

// QuantityGTE applies the GTE predicate on the "quantity" field.
func QuantityGTE(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldGTE(FieldQuantity, v))
}

// QuantityLT applies the LT predicate on the "quantity" field.
func QuantityLT(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldLT(FieldQuantity, v))
}

// QuantityLTE applies the LTE predicate on the "quantity" field.
func QuantityLTE(v int) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.FieldLTE(FieldQuantity, v))
}

// HasSelectedCustomItems applies the HasEdge predicate on the "selected_custom_items" edge.
func HasSelectedCustomItems() predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SelectedCustomItemsTable, SelectedCustomItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSelectedCustomItemsWith applies the HasEdge predicate on the "selected_custom_items" edge with a given conditions (other predicates).
func HasSelectedCustomItemsWith(preds ...predicate.SelectedCustomItem) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := newSelectedCustomItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMasterCustomItem applies the HasEdge predicate on the "master_custom_item" edge.
func HasMasterCustomItem() predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, MasterCustomItemTable, MasterCustomItemColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMasterCustomItemWith applies the HasEdge predicate on the "master_custom_item" edge with a given conditions (other predicates).
func HasMasterCustomItemWith(preds ...predicate.CustomItem) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := newMasterCustomItemStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasOrder applies the HasEdge predicate on the "order" edge.
func HasOrder() predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OrderTable, OrderColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOrderWith applies the HasEdge predicate on the "order" edge with a given conditions (other predicates).
func HasOrderWith(preds ...predicate.Order) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(func(s *sql.Selector) {
		step := newOrderStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OrderCustomItem) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OrderCustomItem) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OrderCustomItem) predicate.OrderCustomItem {
	return predicate.OrderCustomItem(sql.NotPredicates(p))
}
