package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"slices"

	"github.com/codecrafter404/bubble/ent"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
)

// CreateCustomItem is the resolver for the createCustomItem field.
func (r *mutationResolver) CreateCustomItem(ctx context.Context, input ent.CreateCustomItemInput) (*ent.CustomItem, error) {
	client := ent.FromContext(ctx)

	// this ensures that no cycle can be built
	if input.Prev != nil {
		// this ensures that there are not multiple custom items referencing the parent
		exists, err := client.CustomItem.Query().Where(customitem.Prev(*input.Prev)).Exist(ctx)
		if err != nil {
			return nil, fmt.Errorf("Failed to check if reference is already existing: %+v", err)
		}

		if exists {
			return nil, fmt.Errorf("The CustomItem %d ist already depended on", *input.Prev)
		}

		// this ensures that the referenced "prev" custom item exists
		exists, err = client.CustomItem.Query().Where(customitem.ID(*input.Prev)).Exist(ctx)
		if err != nil {
			return nil, fmt.Errorf("Failed to check if the the referenced parent already exists")
		}
		if !exists {
			return nil, fmt.Errorf("The CustomItem with the id %d doesn't exist", *input.Prev)
		}
	}

	// if len(input.VariantIDs) <= 0 {
	// 	return nil, fmt.Errorf("A custom item must at least have one variant")
	// } -> not nessisary; will simply be skipped in the frontedn

	variants, err := client.Item.Query().Where(item.IDIn(input.VariantIDs...)).All(ctx)

	if err != nil {
		return nil, fmt.Errorf("Failed to query relating variants: %+v", err)
	}

	// check if variants exists
	for _, vi := range input.VariantIDs {
		if !slices.ContainsFunc(variants, func(x *ent.Item) bool { return x.ID == vi }) {
			return nil, fmt.Errorf("The related variant %d doesn't exist", vi)
		}
	}

	exists, err := client.CustomItem.Query().Where(customitem.HasVariantsWith(item.IDIn(input.VariantIDs...))).Exist(ctx)

	if err != nil {
		return nil, fmt.Errorf("Failed to check if variants are already used: %+v", err)
	}

	if exists {
		return nil, fmt.Errorf("Some variants are already used by other customitems")
	}

	NotifyEvent(NotificationTypeCustomItemsChanged, r.notification)
	return client.CustomItem.Create().SetInput(input).Save(ctx)
}

// UpdateCustomItem is the resolver for the updateCustomItem field.
func (r *mutationResolver) UpdateCustomItem(ctx context.Context, id int, input ent.UpdateCustomItemInput) (*ent.CustomItem, error) {
	client := ent.FromContext(ctx)

	variants, err := client.Item.Query().Where(item.IDIn(input.AddVariantIDs...)).All(ctx)

	if err != nil {
		return nil, fmt.Errorf("Failed to query relating variants: %+v", err)
	}

	// check if variants exists
	for _, vi := range input.AddVariantIDs {
		if !slices.ContainsFunc(variants, func(x *ent.Item) bool { return x.ID == vi }) {
			return nil, fmt.Errorf("The related variant %d doesn't exist", vi)
		}
	}

	NotifyEvent(NotificationTypeCustomItemsChanged, r.notification)
	return client.CustomItem.UpdateOneID(id).SetInput(input).Save(ctx)
}

// DeleteCustomItem is the resolver for the deleteCustomItem field.
func (r *mutationResolver) DeleteCustomItem(ctx context.Context, id int) (int, error) {
	client := ent.FromContext(ctx)

	exists, err := client.CustomItem.Query().Where(customitem.Prev(id)).Exist(ctx)
	if err != nil {
		return id, fmt.Errorf("Failed to check for deletion conditions: %+v", err)
	}

	if exists {
		return id, fmt.Errorf("You may only delete items at the end of the chain")
	}
	_, err = client.CustomItem.Delete().Where(customitem.ID(id)).Exec(ctx)

	NotifyEvent(NotificationTypeCustomItemsChanged, r.notification)
	return id, err
}

// DeleteCustomItems is the resolver for the deleteCustomItems field.
func (r *mutationResolver) DeleteCustomItems(ctx context.Context, ids []int) ([]int, error) {
	client := ent.FromContext(ctx)

	existing, err := client.CustomItem.Query().All(ctx)
	if err != nil {
		return []int{}, fmt.Errorf("Failed to query customitems to check for validity: %+v", err)
	}

	existing = slices.DeleteFunc(existing, func(e *ent.CustomItem) bool {
		return slices.ContainsFunc(ids, func(id int) bool { return id == e.ID })
	})

	for _, e := range existing {
		if e.Prev == nil {
			continue
		}
		prev_met := slices.ContainsFunc(existing, func(i *ent.CustomItem) bool { return *e.Prev == i.ID })

		if !prev_met {
			return []int{}, fmt.Errorf("You may only delete items at the end of the chain (trying to delete %d)", *e.Prev)
		}
	}

	_, err = client.CustomItem.Delete().Where(customitem.IDIn(ids...)).Exec(ctx)
	NotifyEvent(NotificationTypeCustomItemsChanged, r.notification)
	return ids, err
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
