package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/codecrafter404/bubble/ent"
)

// CreateItem is the resolver for the createItem field.
func (r *mutationResolver) CreateItem(ctx context.Context, input ent.CreateItemInput) (*ent.Item, error) {
	if input.Price < 0 {
		return nil, fmt.Errorf("The price must be >= 0")
	}

	return r.client.Item.Create().SetInput(input).Save(ctx)
}

// UpdateItem is the resolver for the updateItem field.
func (r *mutationResolver) UpdateItem(ctx context.Context, id int, input ent.UpdateItemInput) (*ent.Item, error) {
	if input.Price != nil && *input.Price < 0.0 {
		return nil, fmt.Errorf("The price must be >= 0")
	}

	return r.client.Item.UpdateOneID(id).SetInput(input).Save(ctx)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

type mutationResolver struct{ *Resolver }
