package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"slices"
)

// Notfiy is the resolver for the notfiy field.
func (r *subscriptionResolver) Notfiy(ctx context.Context, typeArg []NotificationType) (<-chan NotificationType, error) {
	res := make(chan NotificationType)
	go func() {
		notification := make(chan NotificationType, r.config.OrderConfig.MaxNotificationQueue)
		r.notification = append(r.notification, &notification)
		for {
			select {
			case <-ctx.Done():
				r.notification = slices.DeleteFunc(r.notification, func(c *chan NotificationType) bool { return c == &notification })
				return
			case n := <-notification:
				if slices.Contains(typeArg, n) {
					res <- n
				}
			}
		}
	}()
	return res, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
