package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"slices"
	"strconv"
	"time"

	"github.com/codecrafter404/bubble/ent"
	"github.com/codecrafter404/bubble/ent/customitem"
	"github.com/codecrafter404/bubble/ent/item"
	"github.com/codecrafter404/bubble/ent/order"
	"github.com/codecrafter404/bubble/ent/ordercustomitem"
	"github.com/codecrafter404/bubble/ent/orderitem"
	"github.com/codecrafter404/bubble/ent/selectedcustomitem"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input ent.CreateOrderInput) (*ent.Order, error) {
	// - calculate total
	total := 0.0

	client := ent.FromContext(ctx)

	orderItems, err := client.OrderItem.Query().Where(orderitem.IDIn(input.ItemIDs...)).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("Failed to query orderitems: %+v", err)
	}

	for _, i := range orderItems {
		price, err := i.QueryItem().Select(item.FieldPrice).Float64(ctx)
		if err != nil {
			return nil, fmt.Errorf("Failed to query price for order item %d", i.ID)
		}
		total += price * float64(i.Quantity)
	}

	orderCustomItems, err := client.OrderCustomItem.Query().Where(ordercustomitem.IDIn(input.CustomItemIDs...)).All(ctx)
	if err != nil {
		return nil, fmt.Errorf("Failed to query ordercustomitems: %+v", err)
	}

	for _, i := range orderCustomItems {
		price, err := i.QuerySelectedCustomItems().QuerySelectedVariants().Aggregate(ent.Sum(item.FieldPrice)).Float64(ctx)
		if err != nil {
			return nil, fmt.Errorf("Failed to query ordercustomitem price: %+v", err)
		}

		total += price * float64(i.Quantity)
	}

	// query and update identifier

	identifier, err := client.Order.Query().Order(ent.Desc(order.FieldSubmitted)).Limit(1).Select(order.FieldIdentifier).String(ctx)
	if _, ok := err.(*ent.NotFoundError); ok {
		identifier = "0"
	} else if err != nil {
		return nil, fmt.Errorf("Failed to query indentifier from prev order: %+v", err)
	}

	identifierInt, err := strconv.Atoi(identifier)
	if err != nil {
		return nil, fmt.Errorf("Failed to parse %s: %+v", identifier, err)
	}

	identifierInt = (identifierInt + 1) % r.config.OrderConfig.MaximalIdentifiers

	identifier = strconv.Itoa(identifierInt)

	// set missing inputs: total, identifier
	res, err := client.Order.Create().SetInput(input).SetIdentifier(identifier).SetTotal(total).SetSubmitted(time.Now()).Save(ctx)
	NotifyEvent(NotificationTypeNewOrder, r.notification)
	return res, err
}

// UpdateOrder is the resolver for the updateOrder field.
func (r *mutationResolver) UpdateOrder(ctx context.Context, id int, input ent.UpdateOrderInput) (*ent.Order, error) {
	client := ent.FromContext(ctx)
	res, err := client.Order.UpdateOneID(id).SetInput(input).Save(ctx)
	NotifyEvent(NotificationTypeOrderUpdated, r.notification)
	return res, err
}

// SelectedCustomItems is the resolver for the selectedCustomItems field.
func (r *createOrderCustomItemInputResolver) SelectedCustomItems(ctx context.Context, obj *ent.CreateOrderCustomItemInput, data []*ent.CreateSelectedCustomItemInput) error {
	client := ent.FromContext(ctx)

	customItemIds := make([]int, len(data))

	// - check if customitem exists
	for i, csci := range data {
		if csci == nil {
			continue
		}
		customItemIds[i] = csci.CustomItemID
	}

	customItems, err := client.CustomItem.Query().Where(customitem.IDIn(customItemIds...)).All(ctx)

	if err != nil {
		return fmt.Errorf("Failed to validate custom items of selected custom item: %+v", customItemIds)
	}

	for _, csci := range data {
		if csci == nil {
			continue
		}
		success := slices.IndexFunc(customItems, func(i *ent.CustomItem) bool { return i.ID == csci.CustomItemID })

		if success == -1 {
			return fmt.Errorf("CustomItem %d doesn't exist", csci.CustomItemID)
		}

		customItem := customItems[success]

		// check if variant is part of custom item
		existingVariants, err := customItem.QueryVariants().Where(item.InStock(true)).All(ctx)
		if err != nil {
			return fmt.Errorf("Failed to query variants of customitem %d: %+v", customItem.ID, err)
		}
		for _, id := range csci.SelectedVariantIDs {
			exists := slices.ContainsFunc(existingVariants, func(j *ent.Item) bool { return j.ID == id })

			if !exists {
				return fmt.Errorf("Selected Variant %d isn't part of custom item %d or currently not in stock", id, customItem.ID)
			}
		}

		// we have to check if non variants have been supplied but also expect customitems without variants (that will simply be skipped on the client)
		if len(csci.SelectedVariantIDs) <= 0 && len(existingVariants) > 0 {
			return fmt.Errorf("The customitem %d must have a variant selected", customItem.ID)
		}

		// check exclusivity
		if len(csci.SelectedVariantIDs) > 1 && customItem.AllowOnlyOne {
			return fmt.Errorf("CustomItem %d allows only one variant to be selected", customItem.ID)
		}

	}

	builders := make([]*ent.SelectedCustomItemCreate, len(data))

	for i := range builders {
		builders[i] = client.SelectedCustomItem.Create().SetInput(*data[i])
	}

	res, err := client.SelectedCustomItem.CreateBulk(builders...).Save(ctx)

	if err != nil {
		return fmt.Errorf("Failed to create selected custom items: %+v", err)
	}

	ids := make([]int, len(data))
	for i, r := range res {
		ids[i] = r.ID
	}

	obj.SelectedCustomItemIDs = ids // OVERWRITE, because the internal field should not be used

	return nil
}

// Items is the resolver for the items field.
func (r *createOrderInputResolver) Items(ctx context.Context, obj *ent.CreateOrderInput, data []*ent.CreateOrderItemInput) error {
	client := ent.FromContext(ctx)

	ids := make([]int, len(data))
	for i, d := range data {
		// check quantity
		if d.Quantity <= 0 {
			return fmt.Errorf("Quantity of item %d should be >= 1", d.ItemID)
		}
		ids[i] = d.ItemID
	}

	// check if items exist
	//TODO: maybe check if items are already occupied by a custom item
	items, err := client.Item.Query().Where(item.And(item.IDIn(ids...), item.InStock(true))).All(ctx)
	if err != nil {
		return fmt.Errorf("Failed to query items: %+v", err)
	}

	builders := make([]*ent.OrderItemCreate, len(data))

	for i, d := range data {
		exists := slices.ContainsFunc(items, func(i *ent.Item) bool { return i.ID == d.ItemID })

		if !exists {
			return fmt.Errorf("The item %d doesn't exist or is not in stock", d.ItemID)
		}
		builders[i] = client.OrderItem.Create().SetInput(*d)
	}

	res, err := client.OrderItem.CreateBulk(builders...).Save(ctx)
	if err != nil {
		return fmt.Errorf("Failed to create orderitems: %+v", err)
	}

	ids = make([]int, len(res))
	for i, r := range res {
		ids[i] = r.ID
	}

	obj.ItemIDs = ids // OVERWRITE, because the internal field should not be used

	return nil
}

// CustomItems is the resolver for the customItems field.
func (r *createOrderInputResolver) CustomItems(ctx context.Context, obj *ent.CreateOrderInput, data []*ent.CreateOrderCustomItemInput) error {
	client := ent.FromContext(ctx)

	for _, d := range data {
		// check quantity
		if d.Quantity <= 0 {
			return fmt.Errorf("OrderCustomItem should have a quantity >= 1")
		}

		// check master order
		master, err := client.CustomItem.Query().Where(customitem.ID(d.MasterCustomItemID)).First(ctx)

		if _, ok := err.(*ent.NotFoundError); ok {
			return fmt.Errorf("CustomItem %d doesn't exist", d.MasterCustomItemID)
		} else if err != nil {
			return fmt.Errorf("Failed to query master custom item: %+v", err)
		}

		if master.Prev != nil {
			return fmt.Errorf("Invalid masterCustomItem specified: %d", master.ID)
		}

		// check if custom item chain is valid AND COMPLEATE
		current := *master
		c := 0
		for {
			if len(d.SelectedCustomItemIDs)-1 < c {
				return fmt.Errorf("CustomItemChain of %d is uncompleate", d.MasterCustomItemID)
			}

			customItem, err := client.SelectedCustomItem.Query().Where(selectedcustomitem.ID(d.SelectedCustomItemIDs[c])).QueryCustomItem().First(ctx)
			if err != nil {
				return fmt.Errorf("Failed so query selected custom item: %+v", err)
			}

			if current.ID != customItem.ID {
				return fmt.Errorf("CustomItem %d is not the (at the right place or) part of the chain", customItem.ID)
			}

			nextCustomItem, err := client.CustomItem.Query().Where(customitem.Prev(current.ID)).First(ctx)
			if _, ok := err.(*ent.NotFoundError); ok {
				if len(d.SelectedCustomItemIDs)-1 != c {
					return fmt.Errorf("SelectedCustomItem Chain is longer than expected (%d > %d)", len(d.SelectedCustomItemIDs), c+1)
				}
				// end of the chain reached
				break
			} else if err != nil {
				return fmt.Errorf("Failed to query next customitem: %+v", err)
			}

			current = *nextCustomItem
			c++
		}

	}

	builders := make([]*ent.OrderCustomItemCreate, len(data))
	for i, d := range data {
		builders[i] = client.OrderCustomItem.Create().SetInput(*d)
	}

	res, err := client.OrderCustomItem.CreateBulk(builders...).Save(ctx)
	if err != nil {
		return fmt.Errorf("Failed to save ordercustomitems: %+v", err)
	}

	ids := make([]int, len(res))
	for i, r := range res {
		ids[i] = r.ID
	}

	obj.CustomItemIDs = ids // OVERWRITE, because the internal field should not be used

	return nil
}
