package gql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"

	"github.com/codecrafter404/bubble/ent"
	"github.com/codecrafter404/bubble/utils"
)

// NextOrder is the resolver for the nextOrder field.
func (r *subscriptionResolver) NextOrder(ctx context.Context, where *ent.OrderWhereInput) (<-chan *ent.Order, error) {
	if where != nil {
		return nil, fmt.Errorf("Where is currently not implemented")
	}
	res := make(chan *ent.Order)

	go func() {
		res <- nil

		subscriber := utils.NewSubscriber()

		*(r.subscribers) = append(*(r.subscribers), &subscriber)

		NotifyEvent(NotificationTypeNewSubscriber, r.notification)

		for {
			select {
			case <-ctx.Done():
				r.disconnect <- subscriber.Id
				return
			case s := <-subscriber.Reciever:
				res <- s
			}
		}
	}()

	return res, nil
}
